<?php
/**
 * DfsSlate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataProjections
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Projections
 *
 * NFL projected stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Acme\FantasyDataProjections;

use \ArrayAccess;
use \Acme\FantasyDataProjections\ObjectSerializer;

/**
 * DfsSlate Class Doc Comment
 *
 * @category Class
 * @package     Acme\FantasyDataProjections
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DfsSlate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DfsSlate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'slate_id' => 'int',
        'operator' => 'string',
        'operator_slate_id' => 'int',
        'operator_name' => 'string',
        'operator_day' => 'string',
        'operator_start_time' => 'string',
        'number_of_games' => 'int',
        'is_multi_day_slate' => 'bool',
        'removed_by_operator' => 'bool',
        'operator_game_type' => 'string',
        'dfs_slate_games' => '\Acme\FantasyDataProjections\\DfsSlateGame[]',
        'dfs_slate_players' => '\Acme\FantasyDataProjections\\DfsSlatePlayer[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'slate_id' => null,
        'operator' => null,
        'operator_slate_id' => null,
        'operator_name' => null,
        'operator_day' => null,
        'operator_start_time' => null,
        'number_of_games' => null,
        'is_multi_day_slate' => null,
        'removed_by_operator' => null,
        'operator_game_type' => null,
        'dfs_slate_games' => null,
        'dfs_slate_players' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'slate_id' => 'SlateID',
        'operator' => 'Operator',
        'operator_slate_id' => 'OperatorSlateID',
        'operator_name' => 'OperatorName',
        'operator_day' => 'OperatorDay',
        'operator_start_time' => 'OperatorStartTime',
        'number_of_games' => 'NumberOfGames',
        'is_multi_day_slate' => 'IsMultiDaySlate',
        'removed_by_operator' => 'RemovedByOperator',
        'operator_game_type' => 'OperatorGameType',
        'dfs_slate_games' => 'DfsSlateGames',
        'dfs_slate_players' => 'DfsSlatePlayers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'slate_id' => 'setSlateId',
        'operator' => 'setOperator',
        'operator_slate_id' => 'setOperatorSlateId',
        'operator_name' => 'setOperatorName',
        'operator_day' => 'setOperatorDay',
        'operator_start_time' => 'setOperatorStartTime',
        'number_of_games' => 'setNumberOfGames',
        'is_multi_day_slate' => 'setIsMultiDaySlate',
        'removed_by_operator' => 'setRemovedByOperator',
        'operator_game_type' => 'setOperatorGameType',
        'dfs_slate_games' => 'setDfsSlateGames',
        'dfs_slate_players' => 'setDfsSlatePlayers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'slate_id' => 'getSlateId',
        'operator' => 'getOperator',
        'operator_slate_id' => 'getOperatorSlateId',
        'operator_name' => 'getOperatorName',
        'operator_day' => 'getOperatorDay',
        'operator_start_time' => 'getOperatorStartTime',
        'number_of_games' => 'getNumberOfGames',
        'is_multi_day_slate' => 'getIsMultiDaySlate',
        'removed_by_operator' => 'getRemovedByOperator',
        'operator_game_type' => 'getOperatorGameType',
        'dfs_slate_games' => 'getDfsSlateGames',
        'dfs_slate_players' => 'getDfsSlatePlayers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['slate_id'] = isset($data['slate_id']) ? $data['slate_id'] : null;
        $this->container['operator'] = isset($data['operator']) ? $data['operator'] : null;
        $this->container['operator_slate_id'] = isset($data['operator_slate_id']) ? $data['operator_slate_id'] : null;
        $this->container['operator_name'] = isset($data['operator_name']) ? $data['operator_name'] : null;
        $this->container['operator_day'] = isset($data['operator_day']) ? $data['operator_day'] : null;
        $this->container['operator_start_time'] = isset($data['operator_start_time']) ? $data['operator_start_time'] : null;
        $this->container['number_of_games'] = isset($data['number_of_games']) ? $data['number_of_games'] : null;
        $this->container['is_multi_day_slate'] = isset($data['is_multi_day_slate']) ? $data['is_multi_day_slate'] : null;
        $this->container['removed_by_operator'] = isset($data['removed_by_operator']) ? $data['removed_by_operator'] : null;
        $this->container['operator_game_type'] = isset($data['operator_game_type']) ? $data['operator_game_type'] : null;
        $this->container['dfs_slate_games'] = isset($data['dfs_slate_games']) ? $data['dfs_slate_games'] : null;
        $this->container['dfs_slate_players'] = isset($data['dfs_slate_players']) ? $data['dfs_slate_players'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets slate_id
     *
     * @return int
     */
    public function getSlateId()
    {
        return $this->container['slate_id'];
    }

    /**
     * Sets slate_id
     *
     * @param int $slate_id slate_id
     *
     * @return $this
     */
    public function setSlateId($slate_id)
    {
        $this->container['slate_id'] = $slate_id;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return string
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param string $operator operator
     *
     * @return $this
     */
    public function setOperator($operator)
    {
        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets operator_slate_id
     *
     * @return int
     */
    public function getOperatorSlateId()
    {
        return $this->container['operator_slate_id'];
    }

    /**
     * Sets operator_slate_id
     *
     * @param int $operator_slate_id operator_slate_id
     *
     * @return $this
     */
    public function setOperatorSlateId($operator_slate_id)
    {
        $this->container['operator_slate_id'] = $operator_slate_id;

        return $this;
    }

    /**
     * Gets operator_name
     *
     * @return string
     */
    public function getOperatorName()
    {
        return $this->container['operator_name'];
    }

    /**
     * Sets operator_name
     *
     * @param string $operator_name operator_name
     *
     * @return $this
     */
    public function setOperatorName($operator_name)
    {
        $this->container['operator_name'] = $operator_name;

        return $this;
    }

    /**
     * Gets operator_day
     *
     * @return string
     */
    public function getOperatorDay()
    {
        return $this->container['operator_day'];
    }

    /**
     * Sets operator_day
     *
     * @param string $operator_day operator_day
     *
     * @return $this
     */
    public function setOperatorDay($operator_day)
    {
        $this->container['operator_day'] = $operator_day;

        return $this;
    }

    /**
     * Gets operator_start_time
     *
     * @return string
     */
    public function getOperatorStartTime()
    {
        return $this->container['operator_start_time'];
    }

    /**
     * Sets operator_start_time
     *
     * @param string $operator_start_time operator_start_time
     *
     * @return $this
     */
    public function setOperatorStartTime($operator_start_time)
    {
        $this->container['operator_start_time'] = $operator_start_time;

        return $this;
    }

    /**
     * Gets number_of_games
     *
     * @return int
     */
    public function getNumberOfGames()
    {
        return $this->container['number_of_games'];
    }

    /**
     * Sets number_of_games
     *
     * @param int $number_of_games number_of_games
     *
     * @return $this
     */
    public function setNumberOfGames($number_of_games)
    {
        $this->container['number_of_games'] = $number_of_games;

        return $this;
    }

    /**
     * Gets is_multi_day_slate
     *
     * @return bool
     */
    public function getIsMultiDaySlate()
    {
        return $this->container['is_multi_day_slate'];
    }

    /**
     * Sets is_multi_day_slate
     *
     * @param bool $is_multi_day_slate is_multi_day_slate
     *
     * @return $this
     */
    public function setIsMultiDaySlate($is_multi_day_slate)
    {
        $this->container['is_multi_day_slate'] = $is_multi_day_slate;

        return $this;
    }

    /**
     * Gets removed_by_operator
     *
     * @return bool
     */
    public function getRemovedByOperator()
    {
        return $this->container['removed_by_operator'];
    }

    /**
     * Sets removed_by_operator
     *
     * @param bool $removed_by_operator removed_by_operator
     *
     * @return $this
     */
    public function setRemovedByOperator($removed_by_operator)
    {
        $this->container['removed_by_operator'] = $removed_by_operator;

        return $this;
    }

    /**
     * Gets operator_game_type
     *
     * @return string
     */
    public function getOperatorGameType()
    {
        return $this->container['operator_game_type'];
    }

    /**
     * Sets operator_game_type
     *
     * @param string $operator_game_type operator_game_type
     *
     * @return $this
     */
    public function setOperatorGameType($operator_game_type)
    {
        $this->container['operator_game_type'] = $operator_game_type;

        return $this;
    }

    /**
     * Gets dfs_slate_games
     *
     * @return \Acme\FantasyDataProjections\\DfsSlateGame[]
     */
    public function getDfsSlateGames()
    {
        return $this->container['dfs_slate_games'];
    }

    /**
     * Sets dfs_slate_games
     *
     * @param \Acme\FantasyDataProjections\\DfsSlateGame[] $dfs_slate_games dfs_slate_games
     *
     * @return $this
     */
    public function setDfsSlateGames($dfs_slate_games)
    {
        $this->container['dfs_slate_games'] = $dfs_slate_games;

        return $this;
    }

    /**
     * Gets dfs_slate_players
     *
     * @return \Acme\FantasyDataProjections\\DfsSlatePlayer[]
     */
    public function getDfsSlatePlayers()
    {
        return $this->container['dfs_slate_players'];
    }

    /**
     * Sets dfs_slate_players
     *
     * @param \Acme\FantasyDataProjections\\DfsSlatePlayer[] $dfs_slate_players dfs_slate_players
     *
     * @return $this
     */
    public function setDfsSlatePlayers($dfs_slate_players)
    {
        $this->container['dfs_slate_players'] = $dfs_slate_players;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

