<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Acme\ProjectionsDFSR
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Projections DFSR
 *
 * NFL v3 Projections DFSR
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Acme\ProjectionsDFSR;

use \Acme\ProjectionsDFSR\Configuration;
use \Acme\ProjectionsDFSR\ApiException;
use \Acme\ProjectionsDFSR\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Acme\ProjectionsDFSR
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dfsrProjectedFantasyDefenseGameStats
     *
     * DFSR Projected Fantasy Defense Game Stats.
     *
     */
    public function testDfsrProjectedFantasyDefenseGameStats()
    {
    }

    /**
     * Test case for dfsrProjectedPlayerGameStats
     *
     * DFSR Projected Player Game Stats.
     *
     */
    public function testDfsrProjectedPlayerGameStats()
    {
    }
}
