<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Acme\FantasyDataStats;

use \Acme\FantasyDataStats\Configuration;
use \Acme\FantasyDataStats\ApiException;
use \Acme\FantasyDataStats\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for areGamesInProgress
     *
     * Are Games In Progress.
     *
     */
    public function testAreGamesInProgress()
    {
    }

    /**
     * Test case for boxScoreByScoreidV
     *
     * Box Score by ScoreID V3.
     *
     */
    public function testBoxScoreByScoreidV()
    {
    }

    /**
     * Test case for boxScoreV
     *
     * Box Score V3.
     *
     */
    public function testBoxScoreV()
    {
    }

    /**
     * Test case for boxScoresDeltaV
     *
     * Box Scores Delta V3.
     *
     */
    public function testBoxScoresDeltaV()
    {
    }

    /**
     * Test case for boxScoresVSimulation
     *
     * Box Scores V3 Simulation.
     *
     */
    public function testBoxScoresVSimulation()
    {
    }

    /**
     * Test case for byeWeeks
     *
     * Bye Weeks.
     *
     */
    public function testByeWeeks()
    {
    }

    /**
     * Test case for dailyFantasyPlayers
     *
     * Daily Fantasy Players.
     *
     */
    public function testDailyFantasyPlayers()
    {
    }

    /**
     * Test case for dailyFantasyScoring
     *
     * Daily Fantasy Scoring.
     *
     */
    public function testDailyFantasyScoring()
    {
    }

    /**
     * Test case for dfsSlatesByDate
     *
     * DFS Slates by Date.
     *
     */
    public function testDfsSlatesByDate()
    {
    }

    /**
     * Test case for dfsSlatesByWeek
     *
     * DFS Slates by Week.
     *
     */
    public function testDfsSlatesByWeek()
    {
    }

    /**
     * Test case for fantasyDefenseGameStats
     *
     * Fantasy Defense Game Stats.
     *
     */
    public function testFantasyDefenseGameStats()
    {
    }

    /**
     * Test case for fantasyDefenseGameStatsByTeam
     *
     * Fantasy Defense Game Stats by Team.
     *
     */
    public function testFantasyDefenseGameStatsByTeam()
    {
    }

    /**
     * Test case for fantasyDefenseSeasonStats
     *
     * Fantasy Defense Season Stats.
     *
     */
    public function testFantasyDefenseSeasonStats()
    {
    }

    /**
     * Test case for fantasyDefenseSeasonStatsByTeam
     *
     * Fantasy Defense Season Stats by Team.
     *
     */
    public function testFantasyDefenseSeasonStatsByTeam()
    {
    }

    /**
     * Test case for fantasyPlayerOwnershipPercentagesSeasonLong
     *
     * Fantasy Player Ownership Percentages (Season-Long).
     *
     */
    public function testFantasyPlayerOwnershipPercentagesSeasonLong()
    {
    }

    /**
     * Test case for fantasyPlayersWithAdp
     *
     * Fantasy Players with ADP.
     *
     */
    public function testFantasyPlayersWithAdp()
    {
    }

    /**
     * Test case for gameStatsBySeasonDeprecatedUseTeamGameStatsInstead
     *
     * Game Stats by Season (Deprecated, use Team Game Stats instead).
     *
     */
    public function testGameStatsBySeasonDeprecatedUseTeamGameStatsInstead()
    {
    }

    /**
     * Test case for gameStatsByWeekDeprecatedUseTeamGameStatsInstead
     *
     * Game Stats by Week (Deprecated, use Team Game Stats instead).
     *
     */
    public function testGameStatsByWeekDeprecatedUseTeamGameStatsInstead()
    {
    }

    /**
     * Test case for idpFantasyPlayersWithAdp
     *
     * IDP Fantasy Players with ADP.
     *
     */
    public function testIdpFantasyPlayersWithAdp()
    {
    }

    /**
     * Test case for injuries
     *
     * Injuries.
     *
     */
    public function testInjuries()
    {
    }

    /**
     * Test case for injuriesByTeam
     *
     * Injuries by Team.
     *
     */
    public function testInjuriesByTeam()
    {
    }

    /**
     * Test case for leagueLeadersBySeason
     *
     * League Leaders by Season.
     *
     */
    public function testLeagueLeadersBySeason()
    {
    }

    /**
     * Test case for leagueLeadersByWeek
     *
     * League Leaders by Week.
     *
     */
    public function testLeagueLeadersByWeek()
    {
    }

    /**
     * Test case for legacyBoxScore
     *
     * Legacy Box Score.
     *
     */
    public function testLegacyBoxScore()
    {
    }

    /**
     * Test case for legacyBoxScores
     *
     * Legacy Box Scores.
     *
     */
    public function testLegacyBoxScores()
    {
    }

    /**
     * Test case for legacyBoxScoresActive
     *
     * Legacy Box Scores Active.
     *
     */
    public function testLegacyBoxScoresActive()
    {
    }

    /**
     * Test case for legacyBoxScoresDelta
     *
     * Legacy Box Scores Delta.
     *
     */
    public function testLegacyBoxScoresDelta()
    {
    }

    /**
     * Test case for legacyBoxScoresDeltaCurrentWeek
     *
     * Legacy Box Scores Delta (Current Week).
     *
     */
    public function testLegacyBoxScoresDeltaCurrentWeek()
    {
    }

    /**
     * Test case for legacyBoxScoresFinal
     *
     * Legacy Box Scores Final.
     *
     */
    public function testLegacyBoxScoresFinal()
    {
    }

    /**
     * Test case for legacyBoxScoresLive
     *
     * Legacy Box Scores Live.
     *
     */
    public function testLegacyBoxScoresLive()
    {
    }

    /**
     * Test case for news
     *
     * News.
     *
     */
    public function testNews()
    {
    }

    /**
     * Test case for newsByDate
     *
     * News by Date.
     *
     */
    public function testNewsByDate()
    {
    }

    /**
     * Test case for newsByPlayer
     *
     * News by Player.
     *
     */
    public function testNewsByPlayer()
    {
    }

    /**
     * Test case for newsByTeam
     *
     * News by Team.
     *
     */
    public function testNewsByTeam()
    {
    }

    /**
     * Test case for playerDetailsByAvailable
     *
     * Player Details by Available.
     *
     */
    public function testPlayerDetailsByAvailable()
    {
    }

    /**
     * Test case for playerDetailsByFreeAgents
     *
     * Player Details by Free Agents.
     *
     */
    public function testPlayerDetailsByFreeAgents()
    {
    }

    /**
     * Test case for playerDetailsByPlayer
     *
     * Player Details by Player.
     *
     */
    public function testPlayerDetailsByPlayer()
    {
    }

    /**
     * Test case for playerDetailsByTeam
     *
     * Player Details by Team.
     *
     */
    public function testPlayerDetailsByTeam()
    {
    }

    /**
     * Test case for playerGameRedZoneStats
     *
     * Player Game Red Zone Stats.
     *
     */
    public function testPlayerGameRedZoneStats()
    {
    }

    /**
     * Test case for playerGameStatsByPlayer
     *
     * Player Game Stats by Player.
     *
     */
    public function testPlayerGameStatsByPlayer()
    {
    }

    /**
     * Test case for playerGameStatsByTeam
     *
     * Player Game Stats by Team.
     *
     */
    public function testPlayerGameStatsByTeam()
    {
    }

    /**
     * Test case for playerGameStatsByWeek
     *
     * Player Game Stats by Week.
     *
     */
    public function testPlayerGameStatsByWeek()
    {
    }

    /**
     * Test case for playerGameStatsByWeekDelta
     *
     * Player Game Stats by Week Delta.
     *
     */
    public function testPlayerGameStatsByWeekDelta()
    {
    }

    /**
     * Test case for playerGameStatsDelta
     *
     * Player Game Stats Delta.
     *
     */
    public function testPlayerGameStatsDelta()
    {
    }

    /**
     * Test case for playerSeasonRedZoneStats
     *
     * Player Season Red Zone Stats.
     *
     */
    public function testPlayerSeasonRedZoneStats()
    {
    }

    /**
     * Test case for playerSeasonStats
     *
     * Player Season Stats.
     *
     */
    public function testPlayerSeasonStats()
    {
    }

    /**
     * Test case for playerSeasonStatsByPlayer
     *
     * Player Season Stats by Player.
     *
     */
    public function testPlayerSeasonStatsByPlayer()
    {
    }

    /**
     * Test case for playerSeasonStatsByTeam
     *
     * Player Season Stats by Team.
     *
     */
    public function testPlayerSeasonStatsByTeam()
    {
    }

    /**
     * Test case for playerSeasonThirdDownStats
     *
     * Player Season Third Down Stats.
     *
     */
    public function testPlayerSeasonThirdDownStats()
    {
    }

    /**
     * Test case for proBowlers
     *
     * Pro Bowlers.
     *
     */
    public function testProBowlers()
    {
    }

    /**
     * Test case for schedule
     *
     * Schedule.
     *
     */
    public function testSchedule()
    {
    }

    /**
     * Test case for scoresBySeason
     *
     * Scores by Season.
     *
     */
    public function testScoresBySeason()
    {
    }

    /**
     * Test case for scoresByWeek
     *
     * Scores by Week.
     *
     */
    public function testScoresByWeek()
    {
    }

    /**
     * Test case for scoresByWeekSimulation
     *
     * Scores by Week Simulation.
     *
     */
    public function testScoresByWeekSimulation()
    {
    }

    /**
     * Test case for seasonCurrent
     *
     * Season Current.
     *
     */
    public function testSeasonCurrent()
    {
    }

    /**
     * Test case for seasonLastCompleted
     *
     * Season Last Completed.
     *
     */
    public function testSeasonLastCompleted()
    {
    }

    /**
     * Test case for seasonUpcoming
     *
     * Season Upcoming.
     *
     */
    public function testSeasonUpcoming()
    {
    }

    /**
     * Test case for stadiums
     *
     * Stadiums.
     *
     */
    public function testStadiums()
    {
    }

    /**
     * Test case for standings
     *
     * Standings.
     *
     */
    public function testStandings()
    {
    }

    /**
     * Test case for teamGameStats
     *
     * Team Game Stats.
     *
     */
    public function testTeamGameStats()
    {
    }

    /**
     * Test case for teamSeasonStats
     *
     * Team Season Stats.
     *
     */
    public function testTeamSeasonStats()
    {
    }

    /**
     * Test case for teamsActive
     *
     * Teams (Active).
     *
     */
    public function testTeamsActive()
    {
    }

    /**
     * Test case for teamsAll
     *
     * Teams (All).
     *
     */
    public function testTeamsAll()
    {
    }

    /**
     * Test case for teamsBySeason
     *
     * Teams by Season.
     *
     */
    public function testTeamsBySeason()
    {
    }

    /**
     * Test case for timeframes
     *
     * Timeframes.
     *
     */
    public function testTimeframes()
    {
    }

    /**
     * Test case for weekCurrent
     *
     * Week Current.
     *
     */
    public function testWeekCurrent()
    {
    }

    /**
     * Test case for weekLastCompleted
     *
     * Week Last Completed.
     *
     */
    public function testWeekLastCompleted()
    {
    }

    /**
     * Test case for weekUpcoming
     *
     * Week Upcoming.
     *
     */
    public function testWeekUpcoming()
    {
    }
}
