<?php
/**
 * GameTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataScores
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Scores
 *
 * NFL schedules, scores, odds, weather, and news API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataScores;

/**
 * GameTest Class Doc Comment
 *
 * @category    Class */
// * @description Game
/**
 * @package     Acme\FantasyDataScores
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GameTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Game"
     */
    public function testGame()
    {
    }

    /**
     * Test attribute "game_key"
     */
    public function testPropertyGameKey()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "season_type"
     */
    public function testPropertySeasonType()
    {
    }

    /**
     * Test attribute "season"
     */
    public function testPropertySeason()
    {
    }

    /**
     * Test attribute "week"
     */
    public function testPropertyWeek()
    {
    }

    /**
     * Test attribute "stadium"
     */
    public function testPropertyStadium()
    {
    }

    /**
     * Test attribute "playing_surface"
     */
    public function testPropertyPlayingSurface()
    {
    }

    /**
     * Test attribute "temperature"
     */
    public function testPropertyTemperature()
    {
    }

    /**
     * Test attribute "humidity"
     */
    public function testPropertyHumidity()
    {
    }

    /**
     * Test attribute "wind_speed"
     */
    public function testPropertyWindSpeed()
    {
    }

    /**
     * Test attribute "away_team"
     */
    public function testPropertyAwayTeam()
    {
    }

    /**
     * Test attribute "home_team"
     */
    public function testPropertyHomeTeam()
    {
    }

    /**
     * Test attribute "away_score"
     */
    public function testPropertyAwayScore()
    {
    }

    /**
     * Test attribute "home_score"
     */
    public function testPropertyHomeScore()
    {
    }

    /**
     * Test attribute "total_score"
     */
    public function testPropertyTotalScore()
    {
    }

    /**
     * Test attribute "over_under"
     */
    public function testPropertyOverUnder()
    {
    }

    /**
     * Test attribute "point_spread"
     */
    public function testPropertyPointSpread()
    {
    }

    /**
     * Test attribute "away_score_quarter1"
     */
    public function testPropertyAwayScoreQuarter1()
    {
    }

    /**
     * Test attribute "away_score_quarter2"
     */
    public function testPropertyAwayScoreQuarter2()
    {
    }

    /**
     * Test attribute "away_score_quarter3"
     */
    public function testPropertyAwayScoreQuarter3()
    {
    }

    /**
     * Test attribute "away_score_quarter4"
     */
    public function testPropertyAwayScoreQuarter4()
    {
    }

    /**
     * Test attribute "away_score_overtime"
     */
    public function testPropertyAwayScoreOvertime()
    {
    }

    /**
     * Test attribute "home_score_quarter1"
     */
    public function testPropertyHomeScoreQuarter1()
    {
    }

    /**
     * Test attribute "home_score_quarter2"
     */
    public function testPropertyHomeScoreQuarter2()
    {
    }

    /**
     * Test attribute "home_score_quarter3"
     */
    public function testPropertyHomeScoreQuarter3()
    {
    }

    /**
     * Test attribute "home_score_quarter4"
     */
    public function testPropertyHomeScoreQuarter4()
    {
    }

    /**
     * Test attribute "home_score_overtime"
     */
    public function testPropertyHomeScoreOvertime()
    {
    }

    /**
     * Test attribute "away_time_of_possession"
     */
    public function testPropertyAwayTimeOfPossession()
    {
    }

    /**
     * Test attribute "home_time_of_possession"
     */
    public function testPropertyHomeTimeOfPossession()
    {
    }

    /**
     * Test attribute "away_first_downs"
     */
    public function testPropertyAwayFirstDowns()
    {
    }

    /**
     * Test attribute "home_first_downs"
     */
    public function testPropertyHomeFirstDowns()
    {
    }

    /**
     * Test attribute "away_first_downs_by_rushing"
     */
    public function testPropertyAwayFirstDownsByRushing()
    {
    }

    /**
     * Test attribute "home_first_downs_by_rushing"
     */
    public function testPropertyHomeFirstDownsByRushing()
    {
    }

    /**
     * Test attribute "away_first_downs_by_passing"
     */
    public function testPropertyAwayFirstDownsByPassing()
    {
    }

    /**
     * Test attribute "home_first_downs_by_passing"
     */
    public function testPropertyHomeFirstDownsByPassing()
    {
    }

    /**
     * Test attribute "away_first_downs_by_penalty"
     */
    public function testPropertyAwayFirstDownsByPenalty()
    {
    }

    /**
     * Test attribute "home_first_downs_by_penalty"
     */
    public function testPropertyHomeFirstDownsByPenalty()
    {
    }

    /**
     * Test attribute "away_offensive_plays"
     */
    public function testPropertyAwayOffensivePlays()
    {
    }

    /**
     * Test attribute "home_offensive_plays"
     */
    public function testPropertyHomeOffensivePlays()
    {
    }

    /**
     * Test attribute "away_offensive_yards"
     */
    public function testPropertyAwayOffensiveYards()
    {
    }

    /**
     * Test attribute "home_offensive_yards"
     */
    public function testPropertyHomeOffensiveYards()
    {
    }

    /**
     * Test attribute "away_offensive_yards_per_play"
     */
    public function testPropertyAwayOffensiveYardsPerPlay()
    {
    }

    /**
     * Test attribute "home_offensive_yards_per_play"
     */
    public function testPropertyHomeOffensiveYardsPerPlay()
    {
    }

    /**
     * Test attribute "away_touchdowns"
     */
    public function testPropertyAwayTouchdowns()
    {
    }

    /**
     * Test attribute "home_touchdowns"
     */
    public function testPropertyHomeTouchdowns()
    {
    }

    /**
     * Test attribute "away_rushing_attempts"
     */
    public function testPropertyAwayRushingAttempts()
    {
    }

    /**
     * Test attribute "home_rushing_attempts"
     */
    public function testPropertyHomeRushingAttempts()
    {
    }

    /**
     * Test attribute "away_rushing_yards"
     */
    public function testPropertyAwayRushingYards()
    {
    }

    /**
     * Test attribute "home_rushing_yards"
     */
    public function testPropertyHomeRushingYards()
    {
    }

    /**
     * Test attribute "away_rushing_yards_per_attempt"
     */
    public function testPropertyAwayRushingYardsPerAttempt()
    {
    }

    /**
     * Test attribute "home_rushing_yards_per_attempt"
     */
    public function testPropertyHomeRushingYardsPerAttempt()
    {
    }

    /**
     * Test attribute "away_rushing_touchdowns"
     */
    public function testPropertyAwayRushingTouchdowns()
    {
    }

    /**
     * Test attribute "home_rushing_touchdowns"
     */
    public function testPropertyHomeRushingTouchdowns()
    {
    }

    /**
     * Test attribute "away_passing_attempts"
     */
    public function testPropertyAwayPassingAttempts()
    {
    }

    /**
     * Test attribute "home_passing_attempts"
     */
    public function testPropertyHomePassingAttempts()
    {
    }

    /**
     * Test attribute "away_passing_completions"
     */
    public function testPropertyAwayPassingCompletions()
    {
    }

    /**
     * Test attribute "home_passing_completions"
     */
    public function testPropertyHomePassingCompletions()
    {
    }

    /**
     * Test attribute "away_passing_yards"
     */
    public function testPropertyAwayPassingYards()
    {
    }

    /**
     * Test attribute "home_passing_yards"
     */
    public function testPropertyHomePassingYards()
    {
    }

    /**
     * Test attribute "away_passing_touchdowns"
     */
    public function testPropertyAwayPassingTouchdowns()
    {
    }

    /**
     * Test attribute "home_passing_touchdowns"
     */
    public function testPropertyHomePassingTouchdowns()
    {
    }

    /**
     * Test attribute "away_passing_interceptions"
     */
    public function testPropertyAwayPassingInterceptions()
    {
    }

    /**
     * Test attribute "home_passing_interceptions"
     */
    public function testPropertyHomePassingInterceptions()
    {
    }

    /**
     * Test attribute "away_passing_yards_per_attempt"
     */
    public function testPropertyAwayPassingYardsPerAttempt()
    {
    }

    /**
     * Test attribute "home_passing_yards_per_attempt"
     */
    public function testPropertyHomePassingYardsPerAttempt()
    {
    }

    /**
     * Test attribute "away_passing_yards_per_completion"
     */
    public function testPropertyAwayPassingYardsPerCompletion()
    {
    }

    /**
     * Test attribute "home_passing_yards_per_completion"
     */
    public function testPropertyHomePassingYardsPerCompletion()
    {
    }

    /**
     * Test attribute "away_completion_percentage"
     */
    public function testPropertyAwayCompletionPercentage()
    {
    }

    /**
     * Test attribute "home_completion_percentage"
     */
    public function testPropertyHomeCompletionPercentage()
    {
    }

    /**
     * Test attribute "away_passer_rating"
     */
    public function testPropertyAwayPasserRating()
    {
    }

    /**
     * Test attribute "home_passer_rating"
     */
    public function testPropertyHomePasserRating()
    {
    }

    /**
     * Test attribute "away_third_down_attempts"
     */
    public function testPropertyAwayThirdDownAttempts()
    {
    }

    /**
     * Test attribute "home_third_down_attempts"
     */
    public function testPropertyHomeThirdDownAttempts()
    {
    }

    /**
     * Test attribute "away_third_down_conversions"
     */
    public function testPropertyAwayThirdDownConversions()
    {
    }

    /**
     * Test attribute "home_third_down_conversions"
     */
    public function testPropertyHomeThirdDownConversions()
    {
    }

    /**
     * Test attribute "away_third_down_percentage"
     */
    public function testPropertyAwayThirdDownPercentage()
    {
    }

    /**
     * Test attribute "home_third_down_percentage"
     */
    public function testPropertyHomeThirdDownPercentage()
    {
    }

    /**
     * Test attribute "away_fourth_down_attempts"
     */
    public function testPropertyAwayFourthDownAttempts()
    {
    }

    /**
     * Test attribute "home_fourth_down_attempts"
     */
    public function testPropertyHomeFourthDownAttempts()
    {
    }

    /**
     * Test attribute "away_fourth_down_conversions"
     */
    public function testPropertyAwayFourthDownConversions()
    {
    }

    /**
     * Test attribute "home_fourth_down_conversions"
     */
    public function testPropertyHomeFourthDownConversions()
    {
    }

    /**
     * Test attribute "away_fourth_down_percentage"
     */
    public function testPropertyAwayFourthDownPercentage()
    {
    }

    /**
     * Test attribute "home_fourth_down_percentage"
     */
    public function testPropertyHomeFourthDownPercentage()
    {
    }

    /**
     * Test attribute "away_red_zone_attempts"
     */
    public function testPropertyAwayRedZoneAttempts()
    {
    }

    /**
     * Test attribute "home_red_zone_attempts"
     */
    public function testPropertyHomeRedZoneAttempts()
    {
    }

    /**
     * Test attribute "away_red_zone_conversions"
     */
    public function testPropertyAwayRedZoneConversions()
    {
    }

    /**
     * Test attribute "home_red_zone_conversions"
     */
    public function testPropertyHomeRedZoneConversions()
    {
    }

    /**
     * Test attribute "away_goal_to_go_attempts"
     */
    public function testPropertyAwayGoalToGoAttempts()
    {
    }

    /**
     * Test attribute "home_goal_to_go_attempts"
     */
    public function testPropertyHomeGoalToGoAttempts()
    {
    }

    /**
     * Test attribute "away_goal_to_go_conversions"
     */
    public function testPropertyAwayGoalToGoConversions()
    {
    }

    /**
     * Test attribute "home_goal_to_go_conversions"
     */
    public function testPropertyHomeGoalToGoConversions()
    {
    }

    /**
     * Test attribute "away_return_yards"
     */
    public function testPropertyAwayReturnYards()
    {
    }

    /**
     * Test attribute "home_return_yards"
     */
    public function testPropertyHomeReturnYards()
    {
    }

    /**
     * Test attribute "away_penalties"
     */
    public function testPropertyAwayPenalties()
    {
    }

    /**
     * Test attribute "home_penalties"
     */
    public function testPropertyHomePenalties()
    {
    }

    /**
     * Test attribute "away_penalty_yards"
     */
    public function testPropertyAwayPenaltyYards()
    {
    }

    /**
     * Test attribute "home_penalty_yards"
     */
    public function testPropertyHomePenaltyYards()
    {
    }

    /**
     * Test attribute "away_fumbles"
     */
    public function testPropertyAwayFumbles()
    {
    }

    /**
     * Test attribute "home_fumbles"
     */
    public function testPropertyHomeFumbles()
    {
    }

    /**
     * Test attribute "away_fumbles_lost"
     */
    public function testPropertyAwayFumblesLost()
    {
    }

    /**
     * Test attribute "home_fumbles_lost"
     */
    public function testPropertyHomeFumblesLost()
    {
    }

    /**
     * Test attribute "away_times_sacked"
     */
    public function testPropertyAwayTimesSacked()
    {
    }

    /**
     * Test attribute "home_times_sacked"
     */
    public function testPropertyHomeTimesSacked()
    {
    }

    /**
     * Test attribute "away_times_sacked_yards"
     */
    public function testPropertyAwayTimesSackedYards()
    {
    }

    /**
     * Test attribute "home_times_sacked_yards"
     */
    public function testPropertyHomeTimesSackedYards()
    {
    }

    /**
     * Test attribute "away_safeties"
     */
    public function testPropertyAwaySafeties()
    {
    }

    /**
     * Test attribute "home_safeties"
     */
    public function testPropertyHomeSafeties()
    {
    }

    /**
     * Test attribute "away_punts"
     */
    public function testPropertyAwayPunts()
    {
    }

    /**
     * Test attribute "home_punts"
     */
    public function testPropertyHomePunts()
    {
    }

    /**
     * Test attribute "away_punt_yards"
     */
    public function testPropertyAwayPuntYards()
    {
    }

    /**
     * Test attribute "home_punt_yards"
     */
    public function testPropertyHomePuntYards()
    {
    }

    /**
     * Test attribute "away_punt_average"
     */
    public function testPropertyAwayPuntAverage()
    {
    }

    /**
     * Test attribute "home_punt_average"
     */
    public function testPropertyHomePuntAverage()
    {
    }

    /**
     * Test attribute "away_giveaways"
     */
    public function testPropertyAwayGiveaways()
    {
    }

    /**
     * Test attribute "home_giveaways"
     */
    public function testPropertyHomeGiveaways()
    {
    }

    /**
     * Test attribute "away_takeaways"
     */
    public function testPropertyAwayTakeaways()
    {
    }

    /**
     * Test attribute "home_takeaways"
     */
    public function testPropertyHomeTakeaways()
    {
    }

    /**
     * Test attribute "away_turnover_differential"
     */
    public function testPropertyAwayTurnoverDifferential()
    {
    }

    /**
     * Test attribute "home_turnover_differential"
     */
    public function testPropertyHomeTurnoverDifferential()
    {
    }

    /**
     * Test attribute "away_kickoffs"
     */
    public function testPropertyAwayKickoffs()
    {
    }

    /**
     * Test attribute "home_kickoffs"
     */
    public function testPropertyHomeKickoffs()
    {
    }

    /**
     * Test attribute "away_kickoffs_in_end_zone"
     */
    public function testPropertyAwayKickoffsInEndZone()
    {
    }

    /**
     * Test attribute "home_kickoffs_in_end_zone"
     */
    public function testPropertyHomeKickoffsInEndZone()
    {
    }

    /**
     * Test attribute "away_kickoff_touchbacks"
     */
    public function testPropertyAwayKickoffTouchbacks()
    {
    }

    /**
     * Test attribute "home_kickoff_touchbacks"
     */
    public function testPropertyHomeKickoffTouchbacks()
    {
    }

    /**
     * Test attribute "away_punts_had_blocked"
     */
    public function testPropertyAwayPuntsHadBlocked()
    {
    }

    /**
     * Test attribute "home_punts_had_blocked"
     */
    public function testPropertyHomePuntsHadBlocked()
    {
    }

    /**
     * Test attribute "away_punt_net_average"
     */
    public function testPropertyAwayPuntNetAverage()
    {
    }

    /**
     * Test attribute "home_punt_net_average"
     */
    public function testPropertyHomePuntNetAverage()
    {
    }

    /**
     * Test attribute "away_extra_point_kicking_attempts"
     */
    public function testPropertyAwayExtraPointKickingAttempts()
    {
    }

    /**
     * Test attribute "home_extra_point_kicking_attempts"
     */
    public function testPropertyHomeExtraPointKickingAttempts()
    {
    }

    /**
     * Test attribute "away_extra_point_kicking_conversions"
     */
    public function testPropertyAwayExtraPointKickingConversions()
    {
    }

    /**
     * Test attribute "home_extra_point_kicking_conversions"
     */
    public function testPropertyHomeExtraPointKickingConversions()
    {
    }

    /**
     * Test attribute "away_extra_points_had_blocked"
     */
    public function testPropertyAwayExtraPointsHadBlocked()
    {
    }

    /**
     * Test attribute "home_extra_points_had_blocked"
     */
    public function testPropertyHomeExtraPointsHadBlocked()
    {
    }

    /**
     * Test attribute "away_extra_point_passing_attempts"
     */
    public function testPropertyAwayExtraPointPassingAttempts()
    {
    }

    /**
     * Test attribute "home_extra_point_passing_attempts"
     */
    public function testPropertyHomeExtraPointPassingAttempts()
    {
    }

    /**
     * Test attribute "away_extra_point_passing_conversions"
     */
    public function testPropertyAwayExtraPointPassingConversions()
    {
    }

    /**
     * Test attribute "home_extra_point_passing_conversions"
     */
    public function testPropertyHomeExtraPointPassingConversions()
    {
    }

    /**
     * Test attribute "away_extra_point_rushing_attempts"
     */
    public function testPropertyAwayExtraPointRushingAttempts()
    {
    }

    /**
     * Test attribute "home_extra_point_rushing_attempts"
     */
    public function testPropertyHomeExtraPointRushingAttempts()
    {
    }

    /**
     * Test attribute "away_extra_point_rushing_conversions"
     */
    public function testPropertyAwayExtraPointRushingConversions()
    {
    }

    /**
     * Test attribute "home_extra_point_rushing_conversions"
     */
    public function testPropertyHomeExtraPointRushingConversions()
    {
    }

    /**
     * Test attribute "away_field_goal_attempts"
     */
    public function testPropertyAwayFieldGoalAttempts()
    {
    }

    /**
     * Test attribute "home_field_goal_attempts"
     */
    public function testPropertyHomeFieldGoalAttempts()
    {
    }

    /**
     * Test attribute "away_field_goals_made"
     */
    public function testPropertyAwayFieldGoalsMade()
    {
    }

    /**
     * Test attribute "home_field_goals_made"
     */
    public function testPropertyHomeFieldGoalsMade()
    {
    }

    /**
     * Test attribute "away_field_goals_had_blocked"
     */
    public function testPropertyAwayFieldGoalsHadBlocked()
    {
    }

    /**
     * Test attribute "home_field_goals_had_blocked"
     */
    public function testPropertyHomeFieldGoalsHadBlocked()
    {
    }

    /**
     * Test attribute "away_punt_returns"
     */
    public function testPropertyAwayPuntReturns()
    {
    }

    /**
     * Test attribute "home_punt_returns"
     */
    public function testPropertyHomePuntReturns()
    {
    }

    /**
     * Test attribute "away_punt_return_yards"
     */
    public function testPropertyAwayPuntReturnYards()
    {
    }

    /**
     * Test attribute "home_punt_return_yards"
     */
    public function testPropertyHomePuntReturnYards()
    {
    }

    /**
     * Test attribute "away_kick_returns"
     */
    public function testPropertyAwayKickReturns()
    {
    }

    /**
     * Test attribute "home_kick_returns"
     */
    public function testPropertyHomeKickReturns()
    {
    }

    /**
     * Test attribute "away_kick_return_yards"
     */
    public function testPropertyAwayKickReturnYards()
    {
    }

    /**
     * Test attribute "home_kick_return_yards"
     */
    public function testPropertyHomeKickReturnYards()
    {
    }

    /**
     * Test attribute "away_interception_returns"
     */
    public function testPropertyAwayInterceptionReturns()
    {
    }

    /**
     * Test attribute "home_interception_returns"
     */
    public function testPropertyHomeInterceptionReturns()
    {
    }

    /**
     * Test attribute "away_interception_return_yards"
     */
    public function testPropertyAwayInterceptionReturnYards()
    {
    }

    /**
     * Test attribute "home_interception_return_yards"
     */
    public function testPropertyHomeInterceptionReturnYards()
    {
    }

    /**
     * Test attribute "away_solo_tackles"
     */
    public function testPropertyAwaySoloTackles()
    {
    }

    /**
     * Test attribute "away_assisted_tackles"
     */
    public function testPropertyAwayAssistedTackles()
    {
    }

    /**
     * Test attribute "away_quarterback_hits"
     */
    public function testPropertyAwayQuarterbackHits()
    {
    }

    /**
     * Test attribute "away_tackles_for_loss"
     */
    public function testPropertyAwayTacklesForLoss()
    {
    }

    /**
     * Test attribute "away_sacks"
     */
    public function testPropertyAwaySacks()
    {
    }

    /**
     * Test attribute "away_sack_yards"
     */
    public function testPropertyAwaySackYards()
    {
    }

    /**
     * Test attribute "away_passes_defended"
     */
    public function testPropertyAwayPassesDefended()
    {
    }

    /**
     * Test attribute "away_fumbles_forced"
     */
    public function testPropertyAwayFumblesForced()
    {
    }

    /**
     * Test attribute "away_fumbles_recovered"
     */
    public function testPropertyAwayFumblesRecovered()
    {
    }

    /**
     * Test attribute "away_fumble_return_yards"
     */
    public function testPropertyAwayFumbleReturnYards()
    {
    }

    /**
     * Test attribute "away_fumble_return_touchdowns"
     */
    public function testPropertyAwayFumbleReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_interception_return_touchdowns"
     */
    public function testPropertyAwayInterceptionReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_blocked_kicks"
     */
    public function testPropertyAwayBlockedKicks()
    {
    }

    /**
     * Test attribute "away_punt_return_touchdowns"
     */
    public function testPropertyAwayPuntReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_punt_return_long"
     */
    public function testPropertyAwayPuntReturnLong()
    {
    }

    /**
     * Test attribute "away_kick_return_touchdowns"
     */
    public function testPropertyAwayKickReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_kick_return_long"
     */
    public function testPropertyAwayKickReturnLong()
    {
    }

    /**
     * Test attribute "away_blocked_kick_return_yards"
     */
    public function testPropertyAwayBlockedKickReturnYards()
    {
    }

    /**
     * Test attribute "away_blocked_kick_return_touchdowns"
     */
    public function testPropertyAwayBlockedKickReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_field_goal_return_yards"
     */
    public function testPropertyAwayFieldGoalReturnYards()
    {
    }

    /**
     * Test attribute "away_field_goal_return_touchdowns"
     */
    public function testPropertyAwayFieldGoalReturnTouchdowns()
    {
    }

    /**
     * Test attribute "away_punt_net_yards"
     */
    public function testPropertyAwayPuntNetYards()
    {
    }

    /**
     * Test attribute "home_solo_tackles"
     */
    public function testPropertyHomeSoloTackles()
    {
    }

    /**
     * Test attribute "home_assisted_tackles"
     */
    public function testPropertyHomeAssistedTackles()
    {
    }

    /**
     * Test attribute "home_quarterback_hits"
     */
    public function testPropertyHomeQuarterbackHits()
    {
    }

    /**
     * Test attribute "home_tackles_for_loss"
     */
    public function testPropertyHomeTacklesForLoss()
    {
    }

    /**
     * Test attribute "home_sacks"
     */
    public function testPropertyHomeSacks()
    {
    }

    /**
     * Test attribute "home_sack_yards"
     */
    public function testPropertyHomeSackYards()
    {
    }

    /**
     * Test attribute "home_passes_defended"
     */
    public function testPropertyHomePassesDefended()
    {
    }

    /**
     * Test attribute "home_fumbles_forced"
     */
    public function testPropertyHomeFumblesForced()
    {
    }

    /**
     * Test attribute "home_fumbles_recovered"
     */
    public function testPropertyHomeFumblesRecovered()
    {
    }

    /**
     * Test attribute "home_fumble_return_yards"
     */
    public function testPropertyHomeFumbleReturnYards()
    {
    }

    /**
     * Test attribute "home_fumble_return_touchdowns"
     */
    public function testPropertyHomeFumbleReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_interception_return_touchdowns"
     */
    public function testPropertyHomeInterceptionReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_blocked_kicks"
     */
    public function testPropertyHomeBlockedKicks()
    {
    }

    /**
     * Test attribute "home_punt_return_touchdowns"
     */
    public function testPropertyHomePuntReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_punt_return_long"
     */
    public function testPropertyHomePuntReturnLong()
    {
    }

    /**
     * Test attribute "home_kick_return_touchdowns"
     */
    public function testPropertyHomeKickReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_kick_return_long"
     */
    public function testPropertyHomeKickReturnLong()
    {
    }

    /**
     * Test attribute "home_blocked_kick_return_yards"
     */
    public function testPropertyHomeBlockedKickReturnYards()
    {
    }

    /**
     * Test attribute "home_blocked_kick_return_touchdowns"
     */
    public function testPropertyHomeBlockedKickReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_field_goal_return_yards"
     */
    public function testPropertyHomeFieldGoalReturnYards()
    {
    }

    /**
     * Test attribute "home_field_goal_return_touchdowns"
     */
    public function testPropertyHomeFieldGoalReturnTouchdowns()
    {
    }

    /**
     * Test attribute "home_punt_net_yards"
     */
    public function testPropertyHomePuntNetYards()
    {
    }

    /**
     * Test attribute "is_game_over"
     */
    public function testPropertyIsGameOver()
    {
    }

    /**
     * Test attribute "game_id"
     */
    public function testPropertyGameId()
    {
    }

    /**
     * Test attribute "stadium_id"
     */
    public function testPropertyStadiumId()
    {
    }

    /**
     * Test attribute "away_two_point_conversion_returns"
     */
    public function testPropertyAwayTwoPointConversionReturns()
    {
    }

    /**
     * Test attribute "home_two_point_conversion_returns"
     */
    public function testPropertyHomeTwoPointConversionReturns()
    {
    }

    /**
     * Test attribute "score_id"
     */
    public function testPropertyScoreId()
    {
    }

    /**
     * Test attribute "stadium_details"
     */
    public function testPropertyStadiumDetails()
    {
    }
}
