<?php
/**
 * ScoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataScores
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Scores
 *
 * NFL schedules, scores, odds, weather, and news API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataScores;

/**
 * ScoreTest Class Doc Comment
 *
 * @category    Class */
// * @description Score
/**
 * @package     Acme\FantasyDataScores
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScoreTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Score"
     */
    public function testScore()
    {
    }

    /**
     * Test attribute "game_key"
     */
    public function testPropertyGameKey()
    {
    }

    /**
     * Test attribute "season_type"
     */
    public function testPropertySeasonType()
    {
    }

    /**
     * Test attribute "season"
     */
    public function testPropertySeason()
    {
    }

    /**
     * Test attribute "week"
     */
    public function testPropertyWeek()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "away_team"
     */
    public function testPropertyAwayTeam()
    {
    }

    /**
     * Test attribute "home_team"
     */
    public function testPropertyHomeTeam()
    {
    }

    /**
     * Test attribute "away_score"
     */
    public function testPropertyAwayScore()
    {
    }

    /**
     * Test attribute "home_score"
     */
    public function testPropertyHomeScore()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "point_spread"
     */
    public function testPropertyPointSpread()
    {
    }

    /**
     * Test attribute "over_under"
     */
    public function testPropertyOverUnder()
    {
    }

    /**
     * Test attribute "quarter"
     */
    public function testPropertyQuarter()
    {
    }

    /**
     * Test attribute "time_remaining"
     */
    public function testPropertyTimeRemaining()
    {
    }

    /**
     * Test attribute "possession"
     */
    public function testPropertyPossession()
    {
    }

    /**
     * Test attribute "down"
     */
    public function testPropertyDown()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "yard_line"
     */
    public function testPropertyYardLine()
    {
    }

    /**
     * Test attribute "yard_line_territory"
     */
    public function testPropertyYardLineTerritory()
    {
    }

    /**
     * Test attribute "red_zone"
     */
    public function testPropertyRedZone()
    {
    }

    /**
     * Test attribute "away_score_quarter1"
     */
    public function testPropertyAwayScoreQuarter1()
    {
    }

    /**
     * Test attribute "away_score_quarter2"
     */
    public function testPropertyAwayScoreQuarter2()
    {
    }

    /**
     * Test attribute "away_score_quarter3"
     */
    public function testPropertyAwayScoreQuarter3()
    {
    }

    /**
     * Test attribute "away_score_quarter4"
     */
    public function testPropertyAwayScoreQuarter4()
    {
    }

    /**
     * Test attribute "away_score_overtime"
     */
    public function testPropertyAwayScoreOvertime()
    {
    }

    /**
     * Test attribute "home_score_quarter1"
     */
    public function testPropertyHomeScoreQuarter1()
    {
    }

    /**
     * Test attribute "home_score_quarter2"
     */
    public function testPropertyHomeScoreQuarter2()
    {
    }

    /**
     * Test attribute "home_score_quarter3"
     */
    public function testPropertyHomeScoreQuarter3()
    {
    }

    /**
     * Test attribute "home_score_quarter4"
     */
    public function testPropertyHomeScoreQuarter4()
    {
    }

    /**
     * Test attribute "home_score_overtime"
     */
    public function testPropertyHomeScoreOvertime()
    {
    }

    /**
     * Test attribute "has_started"
     */
    public function testPropertyHasStarted()
    {
    }

    /**
     * Test attribute "is_in_progress"
     */
    public function testPropertyIsInProgress()
    {
    }

    /**
     * Test attribute "is_over"
     */
    public function testPropertyIsOver()
    {
    }

    /**
     * Test attribute "has1st_quarter_started"
     */
    public function testPropertyHas1stQuarterStarted()
    {
    }

    /**
     * Test attribute "has2nd_quarter_started"
     */
    public function testPropertyHas2ndQuarterStarted()
    {
    }

    /**
     * Test attribute "has3rd_quarter_started"
     */
    public function testPropertyHas3rdQuarterStarted()
    {
    }

    /**
     * Test attribute "has4th_quarter_started"
     */
    public function testPropertyHas4thQuarterStarted()
    {
    }

    /**
     * Test attribute "is_overtime"
     */
    public function testPropertyIsOvertime()
    {
    }

    /**
     * Test attribute "down_and_distance"
     */
    public function testPropertyDownAndDistance()
    {
    }

    /**
     * Test attribute "quarter_description"
     */
    public function testPropertyQuarterDescription()
    {
    }

    /**
     * Test attribute "stadium_id"
     */
    public function testPropertyStadiumId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "geo_lat"
     */
    public function testPropertyGeoLat()
    {
    }

    /**
     * Test attribute "geo_long"
     */
    public function testPropertyGeoLong()
    {
    }

    /**
     * Test attribute "forecast_temp_low"
     */
    public function testPropertyForecastTempLow()
    {
    }

    /**
     * Test attribute "forecast_temp_high"
     */
    public function testPropertyForecastTempHigh()
    {
    }

    /**
     * Test attribute "forecast_description"
     */
    public function testPropertyForecastDescription()
    {
    }

    /**
     * Test attribute "forecast_wind_chill"
     */
    public function testPropertyForecastWindChill()
    {
    }

    /**
     * Test attribute "forecast_wind_speed"
     */
    public function testPropertyForecastWindSpeed()
    {
    }

    /**
     * Test attribute "away_team_money_line"
     */
    public function testPropertyAwayTeamMoneyLine()
    {
    }

    /**
     * Test attribute "home_team_money_line"
     */
    public function testPropertyHomeTeamMoneyLine()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "closed"
     */
    public function testPropertyClosed()
    {
    }

    /**
     * Test attribute "last_play"
     */
    public function testPropertyLastPlay()
    {
    }

    /**
     * Test attribute "day"
     */
    public function testPropertyDay()
    {
    }

    /**
     * Test attribute "date_time"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "away_team_id"
     */
    public function testPropertyAwayTeamId()
    {
    }

    /**
     * Test attribute "home_team_id"
     */
    public function testPropertyHomeTeamId()
    {
    }

    /**
     * Test attribute "global_game_id"
     */
    public function testPropertyGlobalGameId()
    {
    }

    /**
     * Test attribute "global_away_team_id"
     */
    public function testPropertyGlobalAwayTeamId()
    {
    }

    /**
     * Test attribute "global_home_team_id"
     */
    public function testPropertyGlobalHomeTeamId()
    {
    }

    /**
     * Test attribute "point_spread_away_team_money_line"
     */
    public function testPropertyPointSpreadAwayTeamMoneyLine()
    {
    }

    /**
     * Test attribute "point_spread_home_team_money_line"
     */
    public function testPropertyPointSpreadHomeTeamMoneyLine()
    {
    }

    /**
     * Test attribute "score_id"
     */
    public function testPropertyScoreId()
    {
    }

    /**
     * Test attribute "stadium_details"
     */
    public function testPropertyStadiumDetails()
    {
    }
}
