<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataScores
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Scores
 *
 * NFL schedules, scores, odds, weather, and news API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Acme\FantasyDataScores;

use \Acme\FantasyDataScores\Configuration;
use \Acme\FantasyDataScores\ApiException;
use \Acme\FantasyDataScores\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Acme\FantasyDataScores
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for areGamesInProgress
     *
     * Are Games In Progress.
     *
     */
    public function testAreGamesInProgress()
    {
    }

    /**
     * Test case for byeWeeks
     *
     * Bye Weeks.
     *
     */
    public function testByeWeeks()
    {
    }

    /**
     * Test case for gameStatsBySeasonDeprecatedUseTeamGameStatsInstead
     *
     * Game Stats by Season (Deprecated, use Team Game Stats instead).
     *
     */
    public function testGameStatsBySeasonDeprecatedUseTeamGameStatsInstead()
    {
    }

    /**
     * Test case for gameStatsByWeekDeprecatedUseTeamGameStatsInstead
     *
     * Game Stats by Week (Deprecated, use Team Game Stats instead).
     *
     */
    public function testGameStatsByWeekDeprecatedUseTeamGameStatsInstead()
    {
    }

    /**
     * Test case for news
     *
     * News.
     *
     */
    public function testNews()
    {
    }

    /**
     * Test case for newsByDate
     *
     * News by Date.
     *
     */
    public function testNewsByDate()
    {
    }

    /**
     * Test case for newsByPlayer
     *
     * News by Player.
     *
     */
    public function testNewsByPlayer()
    {
    }

    /**
     * Test case for newsByTeam
     *
     * News by Team.
     *
     */
    public function testNewsByTeam()
    {
    }

    /**
     * Test case for schedule
     *
     * Schedule.
     *
     */
    public function testSchedule()
    {
    }

    /**
     * Test case for scoresBySeason
     *
     * Scores by Season.
     *
     */
    public function testScoresBySeason()
    {
    }

    /**
     * Test case for scoresByWeek
     *
     * Scores by Week.
     *
     */
    public function testScoresByWeek()
    {
    }

    /**
     * Test case for scoresByWeekSimulation
     *
     * Scores by Week Simulation.
     *
     */
    public function testScoresByWeekSimulation()
    {
    }

    /**
     * Test case for seasonCurrent
     *
     * Season Current.
     *
     */
    public function testSeasonCurrent()
    {
    }

    /**
     * Test case for seasonLastCompleted
     *
     * Season Last Completed.
     *
     */
    public function testSeasonLastCompleted()
    {
    }

    /**
     * Test case for seasonUpcoming
     *
     * Season Upcoming.
     *
     */
    public function testSeasonUpcoming()
    {
    }

    /**
     * Test case for stadiums
     *
     * Stadiums.
     *
     */
    public function testStadiums()
    {
    }

    /**
     * Test case for standings
     *
     * Standings.
     *
     */
    public function testStandings()
    {
    }

    /**
     * Test case for teamGameStats
     *
     * Team Game Stats.
     *
     */
    public function testTeamGameStats()
    {
    }

    /**
     * Test case for teamSeasonStats
     *
     * Team Season Stats.
     *
     */
    public function testTeamSeasonStats()
    {
    }

    /**
     * Test case for teamsActive
     *
     * Teams (Active).
     *
     */
    public function testTeamsActive()
    {
    }

    /**
     * Test case for teamsAll
     *
     * Teams (All).
     *
     */
    public function testTeamsAll()
    {
    }

    /**
     * Test case for teamsBySeason
     *
     * Teams by Season.
     *
     */
    public function testTeamsBySeason()
    {
    }

    /**
     * Test case for timeframes
     *
     * Timeframes.
     *
     */
    public function testTimeframes()
    {
    }

    /**
     * Test case for weekCurrent
     *
     * Week Current.
     *
     */
    public function testWeekCurrent()
    {
    }

    /**
     * Test case for weekLastCompleted
     *
     * Week Last Completed.
     *
     */
    public function testWeekLastCompleted()
    {
    }

    /**
     * Test case for weekUpcoming
     *
     * Week Upcoming.
     *
     */
    public function testWeekUpcoming()
    {
    }

    /**
     * Test case for xPing
     *
     * X Ping.
     *
     */
    public function testXPing()
    {
    }
}
