<?php
/**
 * PlayerDefense
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Acme\FantasyDataStats;

use \ArrayAccess;
use \Acme\FantasyDataStats\ObjectSerializer;

/**
 * PlayerDefense Class Doc Comment
 *
 * @category Class
 * @package     Acme\FantasyDataStats
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlayerDefense implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PlayerDefense';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'player_game_id' => 'int',
        'player_id' => 'int',
        'short_name' => 'string',
        'name' => 'string',
        'team' => 'string',
        'number' => 'int',
        'position' => 'string',
        'position_category' => 'string',
        'fantasy_position' => 'string',
        'fantasy_points' => 'float',
        'updated' => 'string',
        'tackles' => 'int',
        'solo_tackles' => 'int',
        'assisted_tackles' => 'int',
        'sacks' => 'float',
        'sack_yards' => 'int',
        'fumbles_forced' => 'int',
        'fumbles_recovered' => 'int',
        'passes_defended' => 'int',
        'interceptions' => 'int',
        'interception_return_yards' => 'int',
        'interception_return_touchdowns' => 'int',
        'tackles_for_loss' => 'int',
        'quarterback_hits' => 'int',
        'fumble_return_touchdowns' => 'int',
        'safeties' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'player_game_id' => null,
        'player_id' => null,
        'short_name' => null,
        'name' => null,
        'team' => null,
        'number' => null,
        'position' => null,
        'position_category' => null,
        'fantasy_position' => null,
        'fantasy_points' => null,
        'updated' => null,
        'tackles' => null,
        'solo_tackles' => null,
        'assisted_tackles' => null,
        'sacks' => null,
        'sack_yards' => null,
        'fumbles_forced' => null,
        'fumbles_recovered' => null,
        'passes_defended' => null,
        'interceptions' => null,
        'interception_return_yards' => null,
        'interception_return_touchdowns' => null,
        'tackles_for_loss' => null,
        'quarterback_hits' => null,
        'fumble_return_touchdowns' => null,
        'safeties' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'player_game_id' => 'PlayerGameID',
        'player_id' => 'PlayerID',
        'short_name' => 'ShortName',
        'name' => 'Name',
        'team' => 'Team',
        'number' => 'Number',
        'position' => 'Position',
        'position_category' => 'PositionCategory',
        'fantasy_position' => 'FantasyPosition',
        'fantasy_points' => 'FantasyPoints',
        'updated' => 'Updated',
        'tackles' => 'Tackles',
        'solo_tackles' => 'SoloTackles',
        'assisted_tackles' => 'AssistedTackles',
        'sacks' => 'Sacks',
        'sack_yards' => 'SackYards',
        'fumbles_forced' => 'FumblesForced',
        'fumbles_recovered' => 'FumblesRecovered',
        'passes_defended' => 'PassesDefended',
        'interceptions' => 'Interceptions',
        'interception_return_yards' => 'InterceptionReturnYards',
        'interception_return_touchdowns' => 'InterceptionReturnTouchdowns',
        'tackles_for_loss' => 'TacklesForLoss',
        'quarterback_hits' => 'QuarterbackHits',
        'fumble_return_touchdowns' => 'FumbleReturnTouchdowns',
        'safeties' => 'Safeties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'player_game_id' => 'setPlayerGameId',
        'player_id' => 'setPlayerId',
        'short_name' => 'setShortName',
        'name' => 'setName',
        'team' => 'setTeam',
        'number' => 'setNumber',
        'position' => 'setPosition',
        'position_category' => 'setPositionCategory',
        'fantasy_position' => 'setFantasyPosition',
        'fantasy_points' => 'setFantasyPoints',
        'updated' => 'setUpdated',
        'tackles' => 'setTackles',
        'solo_tackles' => 'setSoloTackles',
        'assisted_tackles' => 'setAssistedTackles',
        'sacks' => 'setSacks',
        'sack_yards' => 'setSackYards',
        'fumbles_forced' => 'setFumblesForced',
        'fumbles_recovered' => 'setFumblesRecovered',
        'passes_defended' => 'setPassesDefended',
        'interceptions' => 'setInterceptions',
        'interception_return_yards' => 'setInterceptionReturnYards',
        'interception_return_touchdowns' => 'setInterceptionReturnTouchdowns',
        'tackles_for_loss' => 'setTacklesForLoss',
        'quarterback_hits' => 'setQuarterbackHits',
        'fumble_return_touchdowns' => 'setFumbleReturnTouchdowns',
        'safeties' => 'setSafeties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'player_game_id' => 'getPlayerGameId',
        'player_id' => 'getPlayerId',
        'short_name' => 'getShortName',
        'name' => 'getName',
        'team' => 'getTeam',
        'number' => 'getNumber',
        'position' => 'getPosition',
        'position_category' => 'getPositionCategory',
        'fantasy_position' => 'getFantasyPosition',
        'fantasy_points' => 'getFantasyPoints',
        'updated' => 'getUpdated',
        'tackles' => 'getTackles',
        'solo_tackles' => 'getSoloTackles',
        'assisted_tackles' => 'getAssistedTackles',
        'sacks' => 'getSacks',
        'sack_yards' => 'getSackYards',
        'fumbles_forced' => 'getFumblesForced',
        'fumbles_recovered' => 'getFumblesRecovered',
        'passes_defended' => 'getPassesDefended',
        'interceptions' => 'getInterceptions',
        'interception_return_yards' => 'getInterceptionReturnYards',
        'interception_return_touchdowns' => 'getInterceptionReturnTouchdowns',
        'tackles_for_loss' => 'getTacklesForLoss',
        'quarterback_hits' => 'getQuarterbackHits',
        'fumble_return_touchdowns' => 'getFumbleReturnTouchdowns',
        'safeties' => 'getSafeties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['player_game_id'] = isset($data['player_game_id']) ? $data['player_game_id'] : null;
        $this->container['player_id'] = isset($data['player_id']) ? $data['player_id'] : null;
        $this->container['short_name'] = isset($data['short_name']) ? $data['short_name'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['team'] = isset($data['team']) ? $data['team'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['position'] = isset($data['position']) ? $data['position'] : null;
        $this->container['position_category'] = isset($data['position_category']) ? $data['position_category'] : null;
        $this->container['fantasy_position'] = isset($data['fantasy_position']) ? $data['fantasy_position'] : null;
        $this->container['fantasy_points'] = isset($data['fantasy_points']) ? $data['fantasy_points'] : null;
        $this->container['updated'] = isset($data['updated']) ? $data['updated'] : null;
        $this->container['tackles'] = isset($data['tackles']) ? $data['tackles'] : null;
        $this->container['solo_tackles'] = isset($data['solo_tackles']) ? $data['solo_tackles'] : null;
        $this->container['assisted_tackles'] = isset($data['assisted_tackles']) ? $data['assisted_tackles'] : null;
        $this->container['sacks'] = isset($data['sacks']) ? $data['sacks'] : null;
        $this->container['sack_yards'] = isset($data['sack_yards']) ? $data['sack_yards'] : null;
        $this->container['fumbles_forced'] = isset($data['fumbles_forced']) ? $data['fumbles_forced'] : null;
        $this->container['fumbles_recovered'] = isset($data['fumbles_recovered']) ? $data['fumbles_recovered'] : null;
        $this->container['passes_defended'] = isset($data['passes_defended']) ? $data['passes_defended'] : null;
        $this->container['interceptions'] = isset($data['interceptions']) ? $data['interceptions'] : null;
        $this->container['interception_return_yards'] = isset($data['interception_return_yards']) ? $data['interception_return_yards'] : null;
        $this->container['interception_return_touchdowns'] = isset($data['interception_return_touchdowns']) ? $data['interception_return_touchdowns'] : null;
        $this->container['tackles_for_loss'] = isset($data['tackles_for_loss']) ? $data['tackles_for_loss'] : null;
        $this->container['quarterback_hits'] = isset($data['quarterback_hits']) ? $data['quarterback_hits'] : null;
        $this->container['fumble_return_touchdowns'] = isset($data['fumble_return_touchdowns']) ? $data['fumble_return_touchdowns'] : null;
        $this->container['safeties'] = isset($data['safeties']) ? $data['safeties'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets player_game_id
     *
     * @return int
     */
    public function getPlayerGameId()
    {
        return $this->container['player_game_id'];
    }

    /**
     * Sets player_game_id
     *
     * @param int $player_game_id player_game_id
     *
     * @return $this
     */
    public function setPlayerGameId($player_game_id)
    {
        $this->container['player_game_id'] = $player_game_id;

        return $this;
    }

    /**
     * Gets player_id
     *
     * @return int
     */
    public function getPlayerId()
    {
        return $this->container['player_id'];
    }

    /**
     * Sets player_id
     *
     * @param int $player_id player_id
     *
     * @return $this
     */
    public function setPlayerId($player_id)
    {
        $this->container['player_id'] = $player_id;

        return $this;
    }

    /**
     * Gets short_name
     *
     * @return string
     */
    public function getShortName()
    {
        return $this->container['short_name'];
    }

    /**
     * Sets short_name
     *
     * @param string $short_name short_name
     *
     * @return $this
     */
    public function setShortName($short_name)
    {
        $this->container['short_name'] = $short_name;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets team
     *
     * @return string
     */
    public function getTeam()
    {
        return $this->container['team'];
    }

    /**
     * Sets team
     *
     * @param string $team team
     *
     * @return $this
     */
    public function setTeam($team)
    {
        $this->container['team'] = $team;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets position
     *
     * @return string
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param string $position position
     *
     * @return $this
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets position_category
     *
     * @return string
     */
    public function getPositionCategory()
    {
        return $this->container['position_category'];
    }

    /**
     * Sets position_category
     *
     * @param string $position_category position_category
     *
     * @return $this
     */
    public function setPositionCategory($position_category)
    {
        $this->container['position_category'] = $position_category;

        return $this;
    }

    /**
     * Gets fantasy_position
     *
     * @return string
     */
    public function getFantasyPosition()
    {
        return $this->container['fantasy_position'];
    }

    /**
     * Sets fantasy_position
     *
     * @param string $fantasy_position fantasy_position
     *
     * @return $this
     */
    public function setFantasyPosition($fantasy_position)
    {
        $this->container['fantasy_position'] = $fantasy_position;

        return $this;
    }

    /**
     * Gets fantasy_points
     *
     * @return float
     */
    public function getFantasyPoints()
    {
        return $this->container['fantasy_points'];
    }

    /**
     * Sets fantasy_points
     *
     * @param float $fantasy_points fantasy_points
     *
     * @return $this
     */
    public function setFantasyPoints($fantasy_points)
    {
        $this->container['fantasy_points'] = $fantasy_points;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return string
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param string $updated updated
     *
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets tackles
     *
     * @return int
     */
    public function getTackles()
    {
        return $this->container['tackles'];
    }

    /**
     * Sets tackles
     *
     * @param int $tackles tackles
     *
     * @return $this
     */
    public function setTackles($tackles)
    {
        $this->container['tackles'] = $tackles;

        return $this;
    }

    /**
     * Gets solo_tackles
     *
     * @return int
     */
    public function getSoloTackles()
    {
        return $this->container['solo_tackles'];
    }

    /**
     * Sets solo_tackles
     *
     * @param int $solo_tackles solo_tackles
     *
     * @return $this
     */
    public function setSoloTackles($solo_tackles)
    {
        $this->container['solo_tackles'] = $solo_tackles;

        return $this;
    }

    /**
     * Gets assisted_tackles
     *
     * @return int
     */
    public function getAssistedTackles()
    {
        return $this->container['assisted_tackles'];
    }

    /**
     * Sets assisted_tackles
     *
     * @param int $assisted_tackles assisted_tackles
     *
     * @return $this
     */
    public function setAssistedTackles($assisted_tackles)
    {
        $this->container['assisted_tackles'] = $assisted_tackles;

        return $this;
    }

    /**
     * Gets sacks
     *
     * @return float
     */
    public function getSacks()
    {
        return $this->container['sacks'];
    }

    /**
     * Sets sacks
     *
     * @param float $sacks sacks
     *
     * @return $this
     */
    public function setSacks($sacks)
    {
        $this->container['sacks'] = $sacks;

        return $this;
    }

    /**
     * Gets sack_yards
     *
     * @return int
     */
    public function getSackYards()
    {
        return $this->container['sack_yards'];
    }

    /**
     * Sets sack_yards
     *
     * @param int $sack_yards sack_yards
     *
     * @return $this
     */
    public function setSackYards($sack_yards)
    {
        $this->container['sack_yards'] = $sack_yards;

        return $this;
    }

    /**
     * Gets fumbles_forced
     *
     * @return int
     */
    public function getFumblesForced()
    {
        return $this->container['fumbles_forced'];
    }

    /**
     * Sets fumbles_forced
     *
     * @param int $fumbles_forced fumbles_forced
     *
     * @return $this
     */
    public function setFumblesForced($fumbles_forced)
    {
        $this->container['fumbles_forced'] = $fumbles_forced;

        return $this;
    }

    /**
     * Gets fumbles_recovered
     *
     * @return int
     */
    public function getFumblesRecovered()
    {
        return $this->container['fumbles_recovered'];
    }

    /**
     * Sets fumbles_recovered
     *
     * @param int $fumbles_recovered fumbles_recovered
     *
     * @return $this
     */
    public function setFumblesRecovered($fumbles_recovered)
    {
        $this->container['fumbles_recovered'] = $fumbles_recovered;

        return $this;
    }

    /**
     * Gets passes_defended
     *
     * @return int
     */
    public function getPassesDefended()
    {
        return $this->container['passes_defended'];
    }

    /**
     * Sets passes_defended
     *
     * @param int $passes_defended passes_defended
     *
     * @return $this
     */
    public function setPassesDefended($passes_defended)
    {
        $this->container['passes_defended'] = $passes_defended;

        return $this;
    }

    /**
     * Gets interceptions
     *
     * @return int
     */
    public function getInterceptions()
    {
        return $this->container['interceptions'];
    }

    /**
     * Sets interceptions
     *
     * @param int $interceptions interceptions
     *
     * @return $this
     */
    public function setInterceptions($interceptions)
    {
        $this->container['interceptions'] = $interceptions;

        return $this;
    }

    /**
     * Gets interception_return_yards
     *
     * @return int
     */
    public function getInterceptionReturnYards()
    {
        return $this->container['interception_return_yards'];
    }

    /**
     * Sets interception_return_yards
     *
     * @param int $interception_return_yards interception_return_yards
     *
     * @return $this
     */
    public function setInterceptionReturnYards($interception_return_yards)
    {
        $this->container['interception_return_yards'] = $interception_return_yards;

        return $this;
    }

    /**
     * Gets interception_return_touchdowns
     *
     * @return int
     */
    public function getInterceptionReturnTouchdowns()
    {
        return $this->container['interception_return_touchdowns'];
    }

    /**
     * Sets interception_return_touchdowns
     *
     * @param int $interception_return_touchdowns interception_return_touchdowns
     *
     * @return $this
     */
    public function setInterceptionReturnTouchdowns($interception_return_touchdowns)
    {
        $this->container['interception_return_touchdowns'] = $interception_return_touchdowns;

        return $this;
    }

    /**
     * Gets tackles_for_loss
     *
     * @return int
     */
    public function getTacklesForLoss()
    {
        return $this->container['tackles_for_loss'];
    }

    /**
     * Sets tackles_for_loss
     *
     * @param int $tackles_for_loss tackles_for_loss
     *
     * @return $this
     */
    public function setTacklesForLoss($tackles_for_loss)
    {
        $this->container['tackles_for_loss'] = $tackles_for_loss;

        return $this;
    }

    /**
     * Gets quarterback_hits
     *
     * @return int
     */
    public function getQuarterbackHits()
    {
        return $this->container['quarterback_hits'];
    }

    /**
     * Sets quarterback_hits
     *
     * @param int $quarterback_hits quarterback_hits
     *
     * @return $this
     */
    public function setQuarterbackHits($quarterback_hits)
    {
        $this->container['quarterback_hits'] = $quarterback_hits;

        return $this;
    }

    /**
     * Gets fumble_return_touchdowns
     *
     * @return int
     */
    public function getFumbleReturnTouchdowns()
    {
        return $this->container['fumble_return_touchdowns'];
    }

    /**
     * Sets fumble_return_touchdowns
     *
     * @param int $fumble_return_touchdowns fumble_return_touchdowns
     *
     * @return $this
     */
    public function setFumbleReturnTouchdowns($fumble_return_touchdowns)
    {
        $this->container['fumble_return_touchdowns'] = $fumble_return_touchdowns;

        return $this;
    }

    /**
     * Gets safeties
     *
     * @return int
     */
    public function getSafeties()
    {
        return $this->container['safeties'];
    }

    /**
     * Sets safeties
     *
     * @param int $safeties safeties
     *
     * @return $this
     */
    public function setSafeties($safeties)
    {
        $this->container['safeties'] = $safeties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

