<?php
/**
 * BoxScoreV3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataStats;

/**
 * BoxScoreV3Test Class Doc Comment
 *
 * @category    Class */
// * @description BoxScoreV3
/**
 * @package     Acme\FantasyDataStats
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BoxScoreV3Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BoxScoreV3"
     */
    public function testBoxScoreV3()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "quarters"
     */
    public function testPropertyQuarters()
    {
    }

    /**
     * Test attribute "team_games"
     */
    public function testPropertyTeamGames()
    {
    }

    /**
     * Test attribute "player_games"
     */
    public function testPropertyPlayerGames()
    {
    }

    /**
     * Test attribute "fantasy_defense_games"
     */
    public function testPropertyFantasyDefenseGames()
    {
    }

    /**
     * Test attribute "scoring_plays"
     */
    public function testPropertyScoringPlays()
    {
    }

    /**
     * Test attribute "scoring_details"
     */
    public function testPropertyScoringDetails()
    {
    }
}
