<?php
/**
 * FantasyPlayerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataStats;

/**
 * FantasyPlayerTest Class Doc Comment
 *
 * @category    Class */
// * @description FantasyPlayer
/**
 * @package     Acme\FantasyDataStats
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FantasyPlayerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FantasyPlayer"
     */
    public function testFantasyPlayer()
    {
    }

    /**
     * Test attribute "fantasy_player_key"
     */
    public function testPropertyFantasyPlayerKey()
    {
    }

    /**
     * Test attribute "player_id"
     */
    public function testPropertyPlayerId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "average_draft_position"
     */
    public function testPropertyAverageDraftPosition()
    {
    }

    /**
     * Test attribute "average_draft_position_ppr"
     */
    public function testPropertyAverageDraftPositionPpr()
    {
    }

    /**
     * Test attribute "bye_week"
     */
    public function testPropertyByeWeek()
    {
    }

    /**
     * Test attribute "last_season_fantasy_points"
     */
    public function testPropertyLastSeasonFantasyPoints()
    {
    }

    /**
     * Test attribute "projected_fantasy_points"
     */
    public function testPropertyProjectedFantasyPoints()
    {
    }

    /**
     * Test attribute "auction_value"
     */
    public function testPropertyAuctionValue()
    {
    }

    /**
     * Test attribute "auction_value_ppr"
     */
    public function testPropertyAuctionValuePpr()
    {
    }

    /**
     * Test attribute "average_draft_position_idp"
     */
    public function testPropertyAverageDraftPositionIdp()
    {
    }
}
