<?php
/**
 * PlayerDefenseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataStats;

/**
 * PlayerDefenseTest Class Doc Comment
 *
 * @category    Class */
// * @description PlayerDefense
/**
 * @package     Acme\FantasyDataStats
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlayerDefenseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlayerDefense"
     */
    public function testPlayerDefense()
    {
    }

    /**
     * Test attribute "player_game_id"
     */
    public function testPropertyPlayerGameId()
    {
    }

    /**
     * Test attribute "player_id"
     */
    public function testPropertyPlayerId()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "position_category"
     */
    public function testPropertyPositionCategory()
    {
    }

    /**
     * Test attribute "fantasy_position"
     */
    public function testPropertyFantasyPosition()
    {
    }

    /**
     * Test attribute "fantasy_points"
     */
    public function testPropertyFantasyPoints()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "tackles"
     */
    public function testPropertyTackles()
    {
    }

    /**
     * Test attribute "solo_tackles"
     */
    public function testPropertySoloTackles()
    {
    }

    /**
     * Test attribute "assisted_tackles"
     */
    public function testPropertyAssistedTackles()
    {
    }

    /**
     * Test attribute "sacks"
     */
    public function testPropertySacks()
    {
    }

    /**
     * Test attribute "sack_yards"
     */
    public function testPropertySackYards()
    {
    }

    /**
     * Test attribute "fumbles_forced"
     */
    public function testPropertyFumblesForced()
    {
    }

    /**
     * Test attribute "fumbles_recovered"
     */
    public function testPropertyFumblesRecovered()
    {
    }

    /**
     * Test attribute "passes_defended"
     */
    public function testPropertyPassesDefended()
    {
    }

    /**
     * Test attribute "interceptions"
     */
    public function testPropertyInterceptions()
    {
    }

    /**
     * Test attribute "interception_return_yards"
     */
    public function testPropertyInterceptionReturnYards()
    {
    }

    /**
     * Test attribute "interception_return_touchdowns"
     */
    public function testPropertyInterceptionReturnTouchdowns()
    {
    }

    /**
     * Test attribute "tackles_for_loss"
     */
    public function testPropertyTacklesForLoss()
    {
    }

    /**
     * Test attribute "quarterback_hits"
     */
    public function testPropertyQuarterbackHits()
    {
    }

    /**
     * Test attribute "fumble_return_touchdowns"
     */
    public function testPropertyFumbleReturnTouchdowns()
    {
    }

    /**
     * Test attribute "safeties"
     */
    public function testPropertySafeties()
    {
    }
}
