<?php
/**
 * PlayerRushingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataStats
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Stats
 *
 * NFL rosters, player stats, team stats, and fantasy stats API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataStats;

/**
 * PlayerRushingTest Class Doc Comment
 *
 * @category    Class */
// * @description PlayerRushing
/**
 * @package     Acme\FantasyDataStats
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlayerRushingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlayerRushing"
     */
    public function testPlayerRushing()
    {
    }

    /**
     * Test attribute "player_game_id"
     */
    public function testPropertyPlayerGameId()
    {
    }

    /**
     * Test attribute "player_id"
     */
    public function testPropertyPlayerId()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "position_category"
     */
    public function testPropertyPositionCategory()
    {
    }

    /**
     * Test attribute "fantasy_position"
     */
    public function testPropertyFantasyPosition()
    {
    }

    /**
     * Test attribute "fantasy_points"
     */
    public function testPropertyFantasyPoints()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "rushing_attempts"
     */
    public function testPropertyRushingAttempts()
    {
    }

    /**
     * Test attribute "rushing_yards"
     */
    public function testPropertyRushingYards()
    {
    }

    /**
     * Test attribute "rushing_touchdowns"
     */
    public function testPropertyRushingTouchdowns()
    {
    }

    /**
     * Test attribute "rushing_long"
     */
    public function testPropertyRushingLong()
    {
    }

    /**
     * Test attribute "rushing_yards_per_attempt"
     */
    public function testPropertyRushingYardsPerAttempt()
    {
    }

    /**
     * Test attribute "fumbles_lost"
     */
    public function testPropertyFumblesLost()
    {
    }

    /**
     * Test attribute "two_point_conversion_runs"
     */
    public function testPropertyTwoPointConversionRuns()
    {
    }
}
