<?php
/**
 * PlayByPlayTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataPlayByPlay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 Play-by-Play
 *
 * NFL play-by-play API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Acme\FantasyDataPlayByPlay;

/**
 * PlayByPlayTest Class Doc Comment
 *
 * @category    Class */
// * @description PlayByPlay
/**
 * @package     Acme\FantasyDataPlayByPlay
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlayByPlayTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlayByPlay"
     */
    public function testPlayByPlay()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "quarters"
     */
    public function testPropertyQuarters()
    {
    }

    /**
     * Test attribute "plays"
     */
    public function testPropertyPlays()
    {
    }
}
