<?php

namespace App\Models\FantasyData;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FantasyDefenseSeason extends Model
{
    use SoftDeletes;

    protected $table = 'fantasy_defense_season';

    protected $fillable = [
        'season_type',
        'season',
        'team',
        'fantasy_points_acme',
        'points_allowed',
        'touchdowns_scored',
        'solo_tackles',
        'assisted_tackles',
        'sacks',
        'sack_yards',
        'passes_defended',
        'fumbles_forced',
        'fumbles_recovered',
        'fumble_return_yards',
        'fumble_return_touchdowns',
        'interceptions',
        'interception_return_yards',
        'interception_return_touchdowns',
        'blocked_kicks',
        'safeties',
        'punt_returns',
        'punt_return_yards',
        'punt_return_touchdowns',
        'punt_return_long',
        'kick_returns',
        'kick_return_yards',
        'kick_return_touchdowns',
        'kick_return_long',
        'blocked_kick_return_touchdowns',
        'field_goal_return_touchdowns',
        'fantasy_points_allowed',
        'quarterback_fantasy_points_allowed',
        'runningback_fantasy_points_allowed',
        'wide_receiver_fantasy_points_allowed',
        'tight_end_fantasy_points_allowed',
        'kicker_fantasy_points_allowed',
        'games',
        'blocked_kick_return_yards',
        'field_goal_return_yards',
        'quarterback_hits',
        'tackles_for_loss',
        'defensive_touchdowns',
        'special_teams_touchdowns',
        'fantasy_points',
        'temperature',
        'humidity',
        'wind_speed',
        'third_down_attempts',
        'third_down_conversions',
        'fourth_down_attempts',
        'fourth_down_conversions',
        'points_allowed_by_defense_special_teams',
        'auction_value',
        'auction_value_p_p_r',
        'two_point_conversion_returns',
        'fantasy_points_fan_duel',
        'fantasy_points_draft_kings',
        'offensive_yards_allowed',
        'player_id',
        'fantasy_points_yahoo',
        'average_draft_position',
        'average_draft_position_p_p_r',
        'team_id',
        'global_team_id',
        'fan_duel_fantasy_points_allowed',
        'fan_duel_quarterback_fantasy_points_allowed',
        'fan_duel_runningback_fantasy_points_allowed',
        'fan_duel_wide_receiver_fantasy_points_allowed',
        'fan_duel_tight_end_fantasy_points_allowed',
        'fan_duel_kicker_fantasy_points_allowed',
        'draft_kings_fantasy_points_allowed',
        'draft_kings_quarterback_fantasy_points_allowed',
        'draft_kings_runningback_fantasy_points_allowed',
        'draft_kings_wide_receiver_fantasy_points_allowed',
        'draft_kings_tight_end_fantasy_points_allowed',
        'draft_kings_kicker_fantasy_points_allowed',
        'yahoo_fantasy_points_allowed',
        'yahoo_quarterback_fantasy_points_allowed',
        'yahoo_runningback_fantasy_points_allowed',
        'yahoo_wide_receiver_fantasy_points_allowed',
        'yahoo_tight_end_fantasy_points_allowed',
        'yahoo_kicker_fantasy_points_allowed',
        'fantasy_points_fantasy_draft',
        'fantasy_draft_fantasy_points_allowed',
        'fantasy_draft_quarterback_fantasy_points_allowed',
        'fantasy_draft_runningback_fantasy_points_allowed',
        'fantasy_draft_wide_receiver_fantasy_points_allowed',
        'fantasy_draft_tight_end_fantasy_points_allowed',
        'fantasy_draft_kicker_fantasy_points_allowed',
        'scoring_details',
    ];

    protected $casts = [
        'season_type' => 'integer',
        'season' => 'integer',
        'team' => 'string',
        'points_allowed' => 'integer',
        'touchdowns_scored' => 'integer',
        'solo_tackles' => 'integer',
        'assisted_tackles' => 'integer',
        'sacks' => 'integer',
        'sack_yards' => 'integer',
        'passes_defended' => 'integer',
        'fumbles_forced' => 'integer',
        'fumbles_recovered' => 'integer',
        'fumble_return_yards' => 'integer',
        'fumble_return_touchdowns' => 'integer',
        'interceptions' => 'integer',
        'interception_return_yards' => 'integer',
        'interception_return_touchdowns' => 'integer',
        'blocked_kicks' => 'integer',
        'safeties' => 'integer',
        'punt_returns' => 'integer',
        'punt_return_yards' => 'integer',
        'punt_return_touchdowns' => 'integer',
        'punt_return_long' => 'integer',
        'kick_returns' => 'integer',
        'kick_return_yards' => 'integer',
        'kick_return_touchdowns' => 'integer',
        'kick_return_long' => 'integer',
        'blocked_kick_return_touchdowns' => 'integer',
        'field_goal_return_touchdowns' => 'integer',
        'fantasy_points_allowed' => 'integer',
        'quarterback_fantasy_points_allowed' => 'integer',
        'runningback_fantasy_points_allowed' => 'integer',
        'wide_receiver_fantasy_points_allowed' => 'integer',
        'tight_end_fantasy_points_allowed' => 'integer',
        'kicker_fantasy_points_allowed' => 'integer',
        'games' => 'integer',
        'blocked_kick_return_yards' => 'integer',
        'field_goal_return_yards' => 'integer',
        'quarterback_hits' => 'integer',
        'tackles_for_loss' => 'integer',
        'defensive_touchdowns' => 'integer',
        'special_teams_touchdowns' => 'integer',
        'fantasy_points' => 'integer',
        'temperature' => 'integer',
        'humidity' => 'integer',
        'wind_speed' => 'integer',
        'third_down_attempts' => 'integer',
        'third_down_conversions' => 'integer',
        'fourth_down_attempts' => 'integer',
        'fourth_down_conversions' => 'integer',
        'points_allowed_by_defense_special_teams' => 'integer',
        'auction_value' => 'integer',
        'auction_value_p_p_r' => 'integer',
        'two_point_conversion_returns' => 'integer',
        'fantasy_points_fan_duel' => 'integer',
        'fantasy_points_draft_kings' => 'integer',
        'offensive_yards_allowed' => 'integer',
        'player_id' => 'integer',
        'fantasy_points_yahoo' => 'integer',
        'average_draft_position' => 'integer',
        'average_draft_position_p_p_r' => 'integer',
        'team_id' => 'integer',
        'global_team_id' => 'integer',
        'fan_duel_fantasy_points_allowed' => 'integer',
        'fan_duel_quarterback_fantasy_points_allowed' => 'integer',
        'fan_duel_runningback_fantasy_points_allowed' => 'integer',
        'fan_duel_wide_receiver_fantasy_points_allowed' => 'integer',
        'fan_duel_tight_end_fantasy_points_allowed' => 'integer',
        'fan_duel_kicker_fantasy_points_allowed' => 'integer',
        'draft_kings_fantasy_points_allowed' => 'integer',
        'draft_kings_quarterback_fantasy_points_allowed' => 'integer',
        'draft_kings_runningback_fantasy_points_allowed' => 'integer',
        'draft_kings_wide_receiver_fantasy_points_allowed' => 'integer',
        'draft_kings_tight_end_fantasy_points_allowed' => 'integer',
        'draft_kings_kicker_fantasy_points_allowed' => 'integer',
        'yahoo_fantasy_points_allowed' => 'integer',
        'yahoo_quarterback_fantasy_points_allowed' => 'integer',
        'yahoo_runningback_fantasy_points_allowed' => 'integer',
        'yahoo_wide_receiver_fantasy_points_allowed' => 'integer',
        'yahoo_tight_end_fantasy_points_allowed' => 'integer',
        'yahoo_kicker_fantasy_points_allowed' => 'integer',
        'fantasy_points_fantasy_draft' => 'integer',
        'fantasy_draft_fantasy_points_allowed' => 'integer',
        'fantasy_draft_quarterback_fantasy_points_allowed' => 'integer',
        'fantasy_draft_runningback_fantasy_points_allowed' => 'integer',
        'fantasy_draft_wide_receiver_fantasy_points_allowed' => 'integer',
        'fantasy_draft_tight_end_fantasy_points_allowed' => 'integer',
        'fantasy_draft_kicker_fantasy_points_allowed' => 'integer',
        'scoring_details' => 'array',
        'fantasy_points_acme' => 'decimal:3',
    ];

    // protected $appends = [
    //     'fantasy_points_acme',

    // ];

    // protected $with = ['fantasyPlayerSeasonFantasyPoint'];

    // public function fantasyPlayerSeasonFantasyPoint()
    // {
    //     return $this->hasManyThrough('App\Models\FantasyPlayerSeasonFantasyPoint', 'App\Models\FantasyData\FantasyPlayer', 'fantasy_player_key', 'fantasy_player_id', 'team', 'id');

    //     //return $this->hasOne('App\Models\FantasyData\FantasyPlayer','fantasy_player_key','team');
    // }

    // public function getFantasyPointsAcmeAttribute($value)
    // {
    //     return isset($this->fantasyPlayerSeasonFantasyPoint()->where('season', $this->season)->where('season_type', $this->season_type)->first()->fantasy_points) ? (float)$this->fantasyPlayerSeasonFantasyPoint()->where('season', $this->season)->where('season_type', $this->season_type)->first()->fantasy_points : (float)0.00;

    //     //       $fantasy_points_acme= ($this->FantasyPlayerSeasonFantasyPoint)?$this->FantasyPlayerSeasonFantasyPoint
    //     // 															->where('season',$this->season)
    //     // 															->where('season_type',$this->season_type)->first()
    //     // 															:'';
    //     // return (!empty($fantasy_points_acme))?$fantasy_points_acme->fantasy_points:'0';
    // }
}
