<?php

namespace App\Models\FantasyData;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlayStat extends Model
{
    use SoftDeletes;

    protected $table = 'play_stat';

    protected $fillable = [
        'play_stat_id',
        'play_id',
        'sequence',
        'player_id',
        'name',
        'team',
        'opponent',
        'home_or_away',
        'direction',
        'updated',
        'created',
        'passing_attempts',
        'passing_completions',
        'passing_yards',
        'passing_touchdowns',
        'passing_interceptions',
        'passing_sacks',
        'passing_sack_yards',
        'rushing_attempts',
        'rushing_yards',
        'rushing_touchdowns',
        'receiving_targets',
        'receptions',
        'receiving_yards',
        'receiving_touchdowns',
        'fumbles',
        'fumbles_lost',
        'two_point_conversion_attempts',
        'two_point_conversion_passes',
        'two_point_conversion_runs',
        'two_point_conversion_receptions',
        'two_point_conversion_returns',
        'solo_tackles',
        'assisted_tackles',
        'tackles_for_loss',
        'sacks',
        'sack_yards',
        'passes_defended',
        'safeties',
        'fumbles_forced',
        'fumbles_recovered',
        'fumble_return_yards',
        'fumble_return_touchdowns',
        'interceptions',
        'interception_return_yards',
        'interception_return_touchdowns',
        'punt_returns',
        'punt_return_yards',
        'punt_return_touchdowns',
        'kick_returns',
        'kick_return_yards',
        'kick_return_touchdowns',
        'blocked_kicks',
        'blocked_kick_returns',
        'blocked_kick_return_yards',
        'blocked_kick_return_touchdowns',
        'field_goal_returns',
        'field_goal_return_yards',
        'field_goal_return_touchdowns',
        'kickoffs',
        'kickoff_yards',
        'kickoff_touchbacks',
        'punts',
        'punt_yards',
        'punt_touchbacks',
        'punts_had_blocked',
        'field_goals_attempted',
        'field_goals_made',
        'field_goals_yards',
        'field_goals_had_blocked',
        'extra_points_attempted',
        'extra_points_made',
        'extra_points_had_blocked',
        'penalties',
        'penalty_yards',
    ];

    protected $casts = [
        'play_stat_id' => 'integer',
        'play_id' => 'integer',
        'sequence' => 'integer',
        'player_id' => 'integer',
        'name' => 'string',
        'team' => 'string',
        'opponent' => 'string',
        'home_or_away' => 'string',
        'direction' => 'string',
        'updated' => 'string',
        'created' => 'string',
        'passing_attempts' => 'integer',
        'passing_completions' => 'integer',
        'passing_yards' => 'integer',
        'passing_touchdowns' => 'integer',
        'passing_interceptions' => 'integer',
        'passing_sacks' => 'integer',
        'passing_sack_yards' => 'integer',
        'rushing_attempts' => 'integer',
        'rushing_yards' => 'integer',
        'rushing_touchdowns' => 'integer',
        'receiving_targets' => 'integer',
        'receptions' => 'integer',
        'receiving_yards' => 'integer',
        'receiving_touchdowns' => 'integer',
        'fumbles' => 'integer',
        'fumbles_lost' => 'integer',
        'two_point_conversion_attempts' => 'integer',
        'two_point_conversion_passes' => 'integer',
        'two_point_conversion_runs' => 'integer',
        'two_point_conversion_receptions' => 'integer',
        'two_point_conversion_returns' => 'integer',
        'solo_tackles' => 'integer',
        'assisted_tackles' => 'integer',
        'tackles_for_loss' => 'integer',
        'sacks' => 'integer',
        'sack_yards' => 'integer',
        'passes_defended' => 'integer',
        'safeties' => 'integer',
        'fumbles_forced' => 'integer',
        'fumbles_recovered' => 'integer',
        'fumble_return_yards' => 'integer',
        'fumble_return_touchdowns' => 'integer',
        'interceptions' => 'integer',
        'interception_return_yards' => 'integer',
        'interception_return_touchdowns' => 'integer',
        'punt_returns' => 'integer',
        'punt_return_yards' => 'integer',
        'punt_return_touchdowns' => 'integer',
        'kick_returns' => 'integer',
        'kick_return_yards' => 'integer',
        'kick_return_touchdowns' => 'integer',
        'blocked_kicks' => 'integer',
        'blocked_kick_returns' => 'integer',
        'blocked_kick_return_yards' => 'integer',
        'blocked_kick_return_touchdowns' => 'integer',
        'field_goal_returns' => 'integer',
        'field_goal_return_yards' => 'integer',
        'field_goal_return_touchdowns' => 'integer',
        'kickoffs' => 'integer',
        'kickoff_yards' => 'integer',
        'kickoff_touchbacks' => 'integer',
        'punts' => 'integer',
        'punt_yards' => 'integer',
        'punt_touchbacks' => 'integer',
        'punts_had_blocked' => 'integer',
        'field_goals_attempted' => 'integer',
        'field_goals_made' => 'integer',
        'field_goals_yards' => 'integer',
        'field_goals_had_blocked' => 'integer',
        'extra_points_attempted' => 'integer',
        'extra_points_made' => 'integer',
        'extra_points_had_blocked' => 'integer',
        'penalties' => 'integer',
        'penalty_yards' => 'integer',
    ];
}
