<?php

namespace App\Models\FantasyData;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlayerSeason extends Model
{
    use SoftDeletes;

    protected $table = 'player_season';

    protected $fillable = [
        'player_id',
        'season_type',
        'season',
        'team',
        'number',
        'name',
        'fantasy_points_acme',
        'position',
        'position_category',
        'activated',
        'played',
        'started',
        'passing_attempts',
        'passing_completions',
        'passing_yards',
        'passing_completion_percentage',
        'passing_yards_per_attempt',
        'passing_yards_per_completion',
        'passing_touchdowns',
        'passing_interceptions',
        'passing_rating',
        'passing_long',
        'passing_sacks',
        'passing_sack_yards',
        'rushing_attempts',
        'rushing_yards',
        'rushing_yards_per_attempt',
        'rushing_touchdowns',
        'rushing_long',
        'receiving_targets',
        'receptions',
        'receiving_yards',
        'receiving_yards_per_reception',
        'receiving_touchdowns',
        'receiving_long',
        'fumbles',
        'fumbles_lost',
        'punt_returns',
        'punt_return_yards',
        'punt_return_yards_per_attempt',
        'punt_return_touchdowns',
        'punt_return_long',
        'kick_returns',
        'kick_return_yards',
        'kick_return_yards_per_attempt',
        'kick_return_touchdowns',
        'kick_return_long',
        'solo_tackles',
        'assisted_tackles',
        'tackles_for_loss',
        'sacks',
        'sack_yards',
        'quarterback_hits',
        'passes_defended',
        'fumbles_forced',
        'fumbles_recovered',
        'fumble_return_yards',
        'fumble_return_touchdowns',
        'interceptions',
        'interception_return_yards',
        'interception_return_touchdowns',
        'blocked_kicks',
        'special_teams_solo_tackles',
        'special_teams_assisted_tackles',
        'misc_solo_tackles',
        'misc_assisted_tackles',
        'punts',
        'punt_yards',
        'punt_average',
        'field_goals_attempted',
        'field_goals_made',
        'field_goals_longest_made',
        'extra_points_made',
        'two_point_conversion_passes',
        'two_point_conversion_runs',
        'two_point_conversion_receptions',
        'fantasy_points',
        'fantasy_points_p_p_r',
        'reception_percentage',
        'receiving_yards_per_target',
        'tackles',
        'offensive_touchdowns',
        'defensive_touchdowns',
        'special_teams_touchdowns',
        'touchdowns',
        'fantasy_position',
        'field_goal_percentage',
        'player_season_id',
        'fumbles_own_recoveries',
        'fumbles_out_of_bounds',
        'kick_return_fair_catches',
        'punt_return_fair_catches',
        'punt_touchbacks',
        'punt_inside20',
        'punt_net_average',
        'extra_points_attempted',
        'blocked_kick_return_touchdowns',
        'field_goal_return_touchdowns',
        'safeties',
        'field_goals_had_blocked',
        'punts_had_blocked',
        'extra_points_had_blocked',
        'punt_long',
        'blocked_kick_return_yards',
        'field_goal_return_yards',
        'punt_net_yards',
        'special_teams_fumbles_forced',
        'special_teams_fumbles_recovered',
        'misc_fumbles_forced',
        'misc_fumbles_recovered',
        'short_name',
        'safeties_allowed',
        'temperature',
        'humidity',
        'wind_speed',
        'offensive_snaps_played',
        'defensive_snaps_played',
        'special_teams_snaps_played',
        'offensive_team_snaps',
        'defensive_team_snaps',
        'special_teams_team_snaps',
        'auction_value',
        'auction_value_p_p_r',
        'two_point_conversion_returns',
        'fantasy_points_fan_duel',
        'field_goals_made0to19',
        'field_goals_made20to29',
        'field_goals_made30to39',
        'field_goals_made40to49',
        'field_goals_made50_plus',
        'fantasy_points_draft_kings',
        'fantasy_points_yahoo',
        'average_draft_position',
        'average_draft_position_p_p_r',
        'team_id',
        'global_team_id',
        'fantasy_points_fantasy_draft',
        'scoring_details',
    ];

    protected $casts = [
        'player_id' => 'integer',
        'season_type' => 'integer',
        'season' => 'integer',
        'team' => 'string',
        'number' => 'integer',
        'name' => 'string',
        'position' => 'string',
        'position_category' => 'string',
        'activated' => 'integer',
        'played' => 'integer',
        'started' => 'integer',
        'passing_attempts' => 'integer',
        'passing_completions' => 'integer',
        'passing_yards' => 'integer',
        'passing_completion_percentage' => 'integer',
        'passing_yards_per_attempt' => 'integer',
        'passing_yards_per_completion' => 'integer',
        'passing_touchdowns' => 'integer',
        'passing_interceptions' => 'integer',
        'passing_rating' => 'integer',
        'passing_long' => 'integer',
        'passing_sacks' => 'integer',
        'passing_sack_yards' => 'integer',
        'rushing_attempts' => 'integer',
        'rushing_yards' => 'integer',
        'rushing_yards_per_attempt' => 'integer',
        'rushing_touchdowns' => 'integer',
        'rushing_long' => 'integer',
        'receiving_targets' => 'integer',
        'receptions' => 'integer',
        'receiving_yards' => 'integer',
        'receiving_yards_per_reception' => 'integer',
        'receiving_touchdowns' => 'integer',
        'receiving_long' => 'integer',
        'fumbles' => 'integer',
        'fumbles_lost' => 'integer',
        'punt_returns' => 'integer',
        'punt_return_yards' => 'integer',
        'punt_return_yards_per_attempt' => 'integer',
        'punt_return_touchdowns' => 'integer',
        'punt_return_long' => 'integer',
        'kick_returns' => 'integer',
        'kick_return_yards' => 'integer',
        'kick_return_yards_per_attempt' => 'integer',
        'kick_return_touchdowns' => 'integer',
        'kick_return_long' => 'integer',
        'solo_tackles' => 'integer',
        'assisted_tackles' => 'integer',
        'tackles_for_loss' => 'integer',
        'sacks' => 'integer',
        'sack_yards' => 'integer',
        'quarterback_hits' => 'integer',
        'passes_defended' => 'integer',
        'fumbles_forced' => 'integer',
        'fumbles_recovered' => 'integer',
        'fumble_return_yards' => 'integer',
        'fumble_return_touchdowns' => 'integer',
        'interceptions' => 'integer',
        'interception_return_yards' => 'integer',
        'interception_return_touchdowns' => 'integer',
        'blocked_kicks' => 'integer',
        'special_teams_solo_tackles' => 'integer',
        'special_teams_assisted_tackles' => 'integer',
        'misc_solo_tackles' => 'integer',
        'misc_assisted_tackles' => 'integer',
        'punts' => 'integer',
        'punt_yards' => 'integer',
        'punt_average' => 'integer',
        'field_goals_attempted' => 'integer',
        'field_goals_made' => 'integer',
        'field_goals_longest_made' => 'integer',
        'extra_points_made' => 'integer',
        'two_point_conversion_passes' => 'integer',
        'two_point_conversion_runs' => 'integer',
        'two_point_conversion_receptions' => 'integer',
        'fantasy_points' => 'integer',
        'fantasy_points_p_p_r' => 'integer',
        'reception_percentage' => 'integer',
        'receiving_yards_per_target' => 'integer',
        'tackles' => 'integer',
        'offensive_touchdowns' => 'integer',
        'defensive_touchdowns' => 'integer',
        'special_teams_touchdowns' => 'integer',
        'touchdowns' => 'integer',
        'fantasy_position' => 'string',
        'field_goal_percentage' => 'integer',
        'player_season_id' => 'integer',
        'fumbles_own_recoveries' => 'integer',
        'fumbles_out_of_bounds' => 'integer',
        'kick_return_fair_catches' => 'integer',
        'punt_return_fair_catches' => 'integer',
        'punt_touchbacks' => 'integer',
        'punt_inside20' => 'integer',
        'punt_net_average' => 'integer',
        'extra_points_attempted' => 'integer',
        'blocked_kick_return_touchdowns' => 'integer',
        'field_goal_return_touchdowns' => 'integer',
        'safeties' => 'integer',
        'field_goals_had_blocked' => 'integer',
        'punts_had_blocked' => 'integer',
        'extra_points_had_blocked' => 'integer',
        'punt_long' => 'integer',
        'blocked_kick_return_yards' => 'integer',
        'field_goal_return_yards' => 'integer',
        'punt_net_yards' => 'integer',
        'special_teams_fumbles_forced' => 'integer',
        'special_teams_fumbles_recovered' => 'integer',
        'misc_fumbles_forced' => 'integer',
        'misc_fumbles_recovered' => 'integer',
        'short_name' => 'string',
        'safeties_allowed' => 'integer',
        'temperature' => 'integer',
        'humidity' => 'integer',
        'wind_speed' => 'integer',
        'offensive_snaps_played' => 'integer',
        'defensive_snaps_played' => 'integer',
        'special_teams_snaps_played' => 'integer',
        'offensive_team_snaps' => 'integer',
        'defensive_team_snaps' => 'integer',
        'special_teams_team_snaps' => 'integer',
        'auction_value' => 'integer',
        'auction_value_p_p_r' => 'integer',
        'two_point_conversion_returns' => 'integer',
        'fantasy_points_fan_duel' => 'integer',
        'field_goals_made0to19' => 'integer',
        'field_goals_made20to29' => 'integer',
        'field_goals_made30to39' => 'integer',
        'field_goals_made40to49' => 'integer',
        'field_goals_made50_plus' => 'integer',
        'fantasy_points_draft_kings' => 'integer',
        'fantasy_points_yahoo' => 'integer',
        'average_draft_position' => 'integer',
        'average_draft_position_p_p_r' => 'integer',
        'team_id' => 'integer',
        'global_team_id' => 'integer',
        'fantasy_points_fantasy_draft' => 'integer',
        'scoring_details' => 'array',
        'fantasy_points_acme' => 'decimal:3',
    ];
    // protected 	$appends = [
    // 	'fantasy_points_acme',
    // ];

    //  protected $with = ['fantasyPlayerSeasonFantasyPoint'];

    // TODO: This really should return a model record but it doesn't:
    // See: http://acmeff.test/players?selectedPosition=RB&season=2019&seasonType=1
    // The fantasy point attribute below it does return a value though.. hmm?
    // public function fantasyPlayerSeasonFantasyPoint()
    // {
    //     // return $this->hasOneThrough('App\Models\FantasyPlayerSeasonFantasyPoint', 'App\Models\FantasyData\FantasyPlayer','player_id','fantasy_player_id','player_id','id');
    //     return $this->hasManyThrough('App\Models\FantasyPlayerSeasonFantasyPoint', 'App\Models\FantasyData\FantasyPlayer', 'player_id', 'fantasy_player_id', 'player_id', 'id')
    //   ->where('season', $this->season)
    //   ->where('season_type', $this->season_type);
    // }

//     public function getFantasyPointsAcmeAttribute($value)
//     {
//         return isset($this->fantasyPlayerSeasonFantasyPoint()->where('season', $this->season)->where('season_type', $this->season_type)->first()->fantasy_points) ? (float)$this->fantasyPlayerSeasonFantasyPoint()->where('season', $this->season)->where('season_type', $this->season_type)->first()->fantasy_points : (float)0.00;
//         //return isset($this->fantasyPlayerSeasonFantasyPoint->fantasy_points) ? $this->fantasyPlayerSeasonFantasyPoint->fantasy_points : 0.00;

//   //       $fantasy_points_acme= ($this->FantasyPlayerSeasonFantasyPoint)?$this->FantasyPlayerSeasonFantasyPoint
//         // 																->where('season',$this->season)
//         // 																->where('season_type',$this->season_type)->first()
//         // 															  :'';
//         // return (!empty($fantasy_points_acme))?$fantasy_points_acme->fantasy_points:'0';
//     }
}
