<?php

namespace App\Models\FantasyData;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlayerDetail extends Model
{
    use SoftDeletes;

    protected $table = 'player_detail';

    protected $fillable = [
        'latest_news',
        'player_id',
        'team',
        'number',
        'first_name',
        'last_name',
        'position',
        'status',
        'height',
        'weight',
        'birth_date',
        'college',
        'experience',
        'fantasy_position',
        'active',
        'position_category',
        'name',
        'age',
        'experience_string',
        'birth_date_string',
        'photo_url',
        'bye_week',
        'upcoming_game_opponent',
        'upcoming_game_week',
        'short_name',
        'average_draft_position',
        'depth_position_category',
        'depth_position',
        'depth_order',
        'depth_display_order',
        'current_team',
        'college_draft_team',
        'college_draft_year',
        'college_draft_round',
        'college_draft_pick',
        'is_undrafted_free_agent',
        'height_feet',
        'height_inches',
        'upcoming_opponent_rank',
        'upcoming_opponent_position_rank',
        'current_status',
        'upcoming_salary',
        'fantasy_alarm_player_id',
        'sport_radar_player_id',
        'rotoworld_player_id',
        'roto_wire_player_id',
        'stats_player_id',
        'sports_direct_player_id',
        'xml_team_player_id',
        'fan_duel_player_id',
        'draft_kings_player_id',
        'yahoo_player_id',
        'injury_status',
        'injury_body_part',
        'injury_start_date',
        'injury_notes',
        'fan_duel_name',
        'draft_kings_name',
        'yahoo_name',
        'fantasy_position_depth_order',
        'injury_practice',
        'injury_practice_description',
        'declared_inactive',
        'upcoming_fan_duel_salary',
        'upcoming_draft_kings_salary',
        'upcoming_yahoo_salary',
        'team_id',
        'global_team_id',
        'fantasy_draft_player_id',
        'fantasy_draft_name',
    ];

    protected $casts = [
        'latest_news' => 'array',
        'player_id' => 'integer',
        'team' => 'string',
        'number' => 'integer',
        'first_name' => 'string',
        'last_name' => 'string',
        'position' => 'string',
        'status' => 'string',
        'height' => 'string',
        'weight' => 'integer',
        'birth_date' => 'string',
        'college' => 'string',
        'experience' => 'integer',
        'fantasy_position' => 'string',
        'active' => 'boolean',
        'position_category' => 'string',
        'name' => 'string',
        'age' => 'integer',
        'experience_string' => 'string',
        'birth_date_string' => 'string',
        'photo_url' => 'string',
        'bye_week' => 'integer',
        'upcoming_game_opponent' => 'string',
        'upcoming_game_week' => 'integer',
        'short_name' => 'string',
        'average_draft_position' => 'integer',
        'depth_position_category' => 'string',
        'depth_position' => 'string',
        'depth_order' => 'integer',
        'depth_display_order' => 'integer',
        'current_team' => 'string',
        'college_draft_team' => 'string',
        'college_draft_year' => 'integer',
        'college_draft_round' => 'integer',
        'college_draft_pick' => 'integer',
        'is_undrafted_free_agent' => 'boolean',
        'height_feet' => 'integer',
        'height_inches' => 'integer',
        'upcoming_opponent_rank' => 'integer',
        'upcoming_opponent_position_rank' => 'integer',
        'current_status' => 'string',
        'upcoming_salary' => 'integer',
        'fantasy_alarm_player_id' => 'integer',
        'sport_radar_player_id' => 'string',
        'rotoworld_player_id' => 'integer',
        'roto_wire_player_id' => 'integer',
        'stats_player_id' => 'integer',
        'sports_direct_player_id' => 'integer',
        'xml_team_player_id' => 'integer',
        'fan_duel_player_id' => 'integer',
        'draft_kings_player_id' => 'integer',
        'yahoo_player_id' => 'integer',
        'injury_status' => 'string',
        'injury_body_part' => 'string',
        'injury_start_date' => 'string',
        'injury_notes' => 'string',
        'fan_duel_name' => 'string',
        'draft_kings_name' => 'string',
        'yahoo_name' => 'string',
        'fantasy_position_depth_order' => 'integer',
        'injury_practice' => 'string',
        'injury_practice_description' => 'string',
        'declared_inactive' => 'boolean',
        'upcoming_fan_duel_salary' => 'integer',
        'upcoming_draft_kings_salary' => 'integer',
        'upcoming_yahoo_salary' => 'integer',
        'team_id' => 'integer',
        'global_team_id' => 'integer',
        'fantasy_draft_player_id' => 'integer',
        'fantasy_draft_name' => 'string',
    ];
}
