<?php

namespace App\Models\FantasyData;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TeamSeason extends Model
{
    use SoftDeletes;

    protected $table = 'team_season';

    protected $fillable = [
        'season_type',
        'season',
        'team',
        'score',
        'opponent_score',
        'total_score',
        'temperature',
        'humidity',
        'wind_speed',
        'over_under',
        'point_spread',
        'score_quarter1',
        'score_quarter2',
        'score_quarter3',
        'score_quarter4',
        'score_overtime',
        'time_of_possession',
        'first_downs',
        'first_downs_by_rushing',
        'first_downs_by_passing',
        'first_downs_by_penalty',
        'offensive_plays',
        'offensive_yards',
        'offensive_yards_per_play',
        'touchdowns',
        'rushing_attempts',
        'rushing_yards',
        'rushing_yards_per_attempt',
        'rushing_touchdowns',
        'passing_attempts',
        'passing_completions',
        'passing_yards',
        'passing_touchdowns',
        'passing_interceptions',
        'passing_yards_per_attempt',
        'passing_yards_per_completion',
        'completion_percentage',
        'passer_rating',
        'third_down_attempts',
        'third_down_conversions',
        'third_down_percentage',
        'fourth_down_attempts',
        'fourth_down_conversions',
        'fourth_down_percentage',
        'red_zone_attempts',
        'red_zone_conversions',
        'goal_to_go_attempts',
        'goal_to_go_conversions',
        'return_yards',
        'penalties',
        'penalty_yards',
        'fumbles',
        'fumbles_lost',
        'times_sacked',
        'times_sacked_yards',
        'quarterback_hits',
        'tackles_for_loss',
        'safeties',
        'punts',
        'punt_yards',
        'punt_average',
        'giveaways',
        'takeaways',
        'turnover_differential',
        'opponent_score_quarter1',
        'opponent_score_quarter2',
        'opponent_score_quarter3',
        'opponent_score_quarter4',
        'opponent_score_overtime',
        'opponent_time_of_possession',
        'opponent_first_downs',
        'opponent_first_downs_by_rushing',
        'opponent_first_downs_by_passing',
        'opponent_first_downs_by_penalty',
        'opponent_offensive_plays',
        'opponent_offensive_yards',
        'opponent_offensive_yards_per_play',
        'opponent_touchdowns',
        'opponent_rushing_attempts',
        'opponent_rushing_yards',
        'opponent_rushing_yards_per_attempt',
        'opponent_rushing_touchdowns',
        'opponent_passing_attempts',
        'opponent_passing_completions',
        'opponent_passing_yards',
        'opponent_passing_touchdowns',
        'opponent_passing_interceptions',
        'opponent_passing_yards_per_attempt',
        'opponent_passing_yards_per_completion',
        'opponent_completion_percentage',
        'opponent_passer_rating',
        'opponent_third_down_attempts',
        'opponent_third_down_conversions',
        'opponent_third_down_percentage',
        'opponent_fourth_down_attempts',
        'opponent_fourth_down_conversions',
        'opponent_fourth_down_percentage',
        'opponent_red_zone_attempts',
        'opponent_red_zone_conversions',
        'opponent_goal_to_go_attempts',
        'opponent_goal_to_go_conversions',
        'opponent_return_yards',
        'opponent_penalties',
        'opponent_penalty_yards',
        'opponent_fumbles',
        'opponent_fumbles_lost',
        'opponent_times_sacked',
        'opponent_times_sacked_yards',
        'opponent_quarterback_hits',
        'opponent_tackles_for_loss',
        'opponent_safeties',
        'opponent_punts',
        'opponent_punt_yards',
        'opponent_punt_average',
        'opponent_giveaways',
        'opponent_takeaways',
        'opponent_turnover_differential',
        'red_zone_percentage',
        'goal_to_go_percentage',
        'quarterback_hits_differential',
        'tackles_for_loss_differential',
        'quarterback_sacks_differential',
        'tackles_for_loss_percentage',
        'quarterback_hits_percentage',
        'times_sacked_percentage',
        'opponent_red_zone_percentage',
        'opponent_goal_to_go_percentage',
        'opponent_quarterback_hits_differential',
        'opponent_tackles_for_loss_differential',
        'opponent_quarterback_sacks_differential',
        'opponent_tackles_for_loss_percentage',
        'opponent_quarterback_hits_percentage',
        'opponent_times_sacked_percentage',
        'kickoffs',
        'kickoffs_in_end_zone',
        'kickoff_touchbacks',
        'punts_had_blocked',
        'punt_net_average',
        'extra_point_kicking_attempts',
        'extra_point_kicking_conversions',
        'extra_points_had_blocked',
        'extra_point_passing_attempts',
        'extra_point_passing_conversions',
        'extra_point_rushing_attempts',
        'extra_point_rushing_conversions',
        'field_goal_attempts',
        'field_goals_made',
        'field_goals_had_blocked',
        'punt_returns',
        'punt_return_yards',
        'kick_returns',
        'kick_return_yards',
        'interception_returns',
        'interception_return_yards',
        'opponent_kickoffs',
        'opponent_kickoffs_in_end_zone',
        'opponent_kickoff_touchbacks',
        'opponent_punts_had_blocked',
        'opponent_punt_net_average',
        'opponent_extra_point_kicking_attempts',
        'opponent_extra_point_kicking_conversions',
        'opponent_extra_points_had_blocked',
        'opponent_extra_point_passing_attempts',
        'opponent_extra_point_passing_conversions',
        'opponent_extra_point_rushing_attempts',
        'opponent_extra_point_rushing_conversions',
        'opponent_field_goal_attempts',
        'opponent_field_goals_made',
        'opponent_field_goals_had_blocked',
        'opponent_punt_returns',
        'opponent_punt_return_yards',
        'opponent_kick_returns',
        'opponent_kick_return_yards',
        'opponent_interception_returns',
        'opponent_interception_return_yards',
        'solo_tackles',
        'assisted_tackles',
        'sacks',
        'sack_yards',
        'passes_defended',
        'fumbles_forced',
        'fumbles_recovered',
        'fumble_return_yards',
        'fumble_return_touchdowns',
        'interception_return_touchdowns',
        'blocked_kicks',
        'punt_return_touchdowns',
        'punt_return_long',
        'kick_return_touchdowns',
        'kick_return_long',
        'blocked_kick_return_yards',
        'blocked_kick_return_touchdowns',
        'field_goal_return_yards',
        'field_goal_return_touchdowns',
        'punt_net_yards',
        'opponent_solo_tackles',
        'opponent_assisted_tackles',
        'opponent_sacks',
        'opponent_sack_yards',
        'opponent_passes_defended',
        'opponent_fumbles_forced',
        'opponent_fumbles_recovered',
        'opponent_fumble_return_yards',
        'opponent_fumble_return_touchdowns',
        'opponent_interception_return_touchdowns',
        'opponent_blocked_kicks',
        'opponent_punt_return_touchdowns',
        'opponent_punt_return_long',
        'opponent_kick_return_touchdowns',
        'opponent_kick_return_long',
        'opponent_blocked_kick_return_yards',
        'opponent_blocked_kick_return_touchdowns',
        'opponent_field_goal_return_yards',
        'opponent_field_goal_return_touchdowns',
        'opponent_punt_net_yards',
        'team_name',
        'games',
        'passing_dropbacks',
        'opponent_passing_dropbacks',
        'team_season_id',
        'point_differential',
        'passing_interception_percentage',
        'punt_return_average',
        'kick_return_average',
        'extra_point_percentage',
        'field_goal_percentage',
        'opponent_passing_interception_percentage',
        'opponent_punt_return_average',
        'opponent_kick_return_average',
        'opponent_extra_point_percentage',
        'opponent_field_goal_percentage',
        'penalty_yard_differential',
        'punt_return_yard_differential',
        'kick_return_yard_differential',
        'two_point_conversion_returns',
        'opponent_two_point_conversion_returns',
        'team_id',
        'global_team_id',
    ];

    protected $casts = [
        'season_type' => 'integer',
        'season' => 'integer',
        'team' => 'string',
        'score' => 'integer',
        'opponent_score' => 'integer',
        'total_score' => 'integer',
        'temperature' => 'integer',
        'humidity' => 'integer',
        'wind_speed' => 'integer',
        'over_under' => 'integer',
        'point_spread' => 'integer',
        'score_quarter1' => 'integer',
        'score_quarter2' => 'integer',
        'score_quarter3' => 'integer',
        'score_quarter4' => 'integer',
        'score_overtime' => 'integer',
        'time_of_possession' => 'string',
        'first_downs' => 'integer',
        'first_downs_by_rushing' => 'integer',
        'first_downs_by_passing' => 'integer',
        'first_downs_by_penalty' => 'integer',
        'offensive_plays' => 'integer',
        'offensive_yards' => 'integer',
        'offensive_yards_per_play' => 'integer',
        'touchdowns' => 'integer',
        'rushing_attempts' => 'integer',
        'rushing_yards' => 'integer',
        'rushing_yards_per_attempt' => 'integer',
        'rushing_touchdowns' => 'integer',
        'passing_attempts' => 'integer',
        'passing_completions' => 'integer',
        'passing_yards' => 'integer',
        'passing_touchdowns' => 'integer',
        'passing_interceptions' => 'integer',
        'passing_yards_per_attempt' => 'integer',
        'passing_yards_per_completion' => 'integer',
        'completion_percentage' => 'integer',
        'passer_rating' => 'integer',
        'third_down_attempts' => 'integer',
        'third_down_conversions' => 'integer',
        'third_down_percentage' => 'integer',
        'fourth_down_attempts' => 'integer',
        'fourth_down_conversions' => 'integer',
        'fourth_down_percentage' => 'integer',
        'red_zone_attempts' => 'integer',
        'red_zone_conversions' => 'integer',
        'goal_to_go_attempts' => 'integer',
        'goal_to_go_conversions' => 'integer',
        'return_yards' => 'integer',
        'penalties' => 'integer',
        'penalty_yards' => 'integer',
        'fumbles' => 'integer',
        'fumbles_lost' => 'integer',
        'times_sacked' => 'integer',
        'times_sacked_yards' => 'integer',
        'quarterback_hits' => 'integer',
        'tackles_for_loss' => 'integer',
        'safeties' => 'integer',
        'punts' => 'integer',
        'punt_yards' => 'integer',
        'punt_average' => 'integer',
        'giveaways' => 'integer',
        'takeaways' => 'integer',
        'turnover_differential' => 'integer',
        'opponent_score_quarter1' => 'integer',
        'opponent_score_quarter2' => 'integer',
        'opponent_score_quarter3' => 'integer',
        'opponent_score_quarter4' => 'integer',
        'opponent_score_overtime' => 'integer',
        'opponent_time_of_possession' => 'string',
        'opponent_first_downs' => 'integer',
        'opponent_first_downs_by_rushing' => 'integer',
        'opponent_first_downs_by_passing' => 'integer',
        'opponent_first_downs_by_penalty' => 'integer',
        'opponent_offensive_plays' => 'integer',
        'opponent_offensive_yards' => 'integer',
        'opponent_offensive_yards_per_play' => 'integer',
        'opponent_touchdowns' => 'integer',
        'opponent_rushing_attempts' => 'integer',
        'opponent_rushing_yards' => 'integer',
        'opponent_rushing_yards_per_attempt' => 'integer',
        'opponent_rushing_touchdowns' => 'integer',
        'opponent_passing_attempts' => 'integer',
        'opponent_passing_completions' => 'integer',
        'opponent_passing_yards' => 'integer',
        'opponent_passing_touchdowns' => 'integer',
        'opponent_passing_interceptions' => 'integer',
        'opponent_passing_yards_per_attempt' => 'integer',
        'opponent_passing_yards_per_completion' => 'integer',
        'opponent_completion_percentage' => 'integer',
        'opponent_passer_rating' => 'integer',
        'opponent_third_down_attempts' => 'integer',
        'opponent_third_down_conversions' => 'integer',
        'opponent_third_down_percentage' => 'integer',
        'opponent_fourth_down_attempts' => 'integer',
        'opponent_fourth_down_conversions' => 'integer',
        'opponent_fourth_down_percentage' => 'integer',
        'opponent_red_zone_attempts' => 'integer',
        'opponent_red_zone_conversions' => 'integer',
        'opponent_goal_to_go_attempts' => 'integer',
        'opponent_goal_to_go_conversions' => 'integer',
        'opponent_return_yards' => 'integer',
        'opponent_penalties' => 'integer',
        'opponent_penalty_yards' => 'integer',
        'opponent_fumbles' => 'integer',
        'opponent_fumbles_lost' => 'integer',
        'opponent_times_sacked' => 'integer',
        'opponent_times_sacked_yards' => 'integer',
        'opponent_quarterback_hits' => 'integer',
        'opponent_tackles_for_loss' => 'integer',
        'opponent_safeties' => 'integer',
        'opponent_punts' => 'integer',
        'opponent_punt_yards' => 'integer',
        'opponent_punt_average' => 'integer',
        'opponent_giveaways' => 'integer',
        'opponent_takeaways' => 'integer',
        'opponent_turnover_differential' => 'integer',
        'red_zone_percentage' => 'integer',
        'goal_to_go_percentage' => 'integer',
        'quarterback_hits_differential' => 'integer',
        'tackles_for_loss_differential' => 'integer',
        'quarterback_sacks_differential' => 'integer',
        'tackles_for_loss_percentage' => 'integer',
        'quarterback_hits_percentage' => 'integer',
        'times_sacked_percentage' => 'integer',
        'opponent_red_zone_percentage' => 'integer',
        'opponent_goal_to_go_percentage' => 'integer',
        'opponent_quarterback_hits_differential' => 'integer',
        'opponent_tackles_for_loss_differential' => 'integer',
        'opponent_quarterback_sacks_differential' => 'integer',
        'opponent_tackles_for_loss_percentage' => 'integer',
        'opponent_quarterback_hits_percentage' => 'integer',
        'opponent_times_sacked_percentage' => 'integer',
        'kickoffs' => 'integer',
        'kickoffs_in_end_zone' => 'integer',
        'kickoff_touchbacks' => 'integer',
        'punts_had_blocked' => 'integer',
        'punt_net_average' => 'integer',
        'extra_point_kicking_attempts' => 'integer',
        'extra_point_kicking_conversions' => 'integer',
        'extra_points_had_blocked' => 'integer',
        'extra_point_passing_attempts' => 'integer',
        'extra_point_passing_conversions' => 'integer',
        'extra_point_rushing_attempts' => 'integer',
        'extra_point_rushing_conversions' => 'integer',
        'field_goal_attempts' => 'integer',
        'field_goals_made' => 'integer',
        'field_goals_had_blocked' => 'integer',
        'punt_returns' => 'integer',
        'punt_return_yards' => 'integer',
        'kick_returns' => 'integer',
        'kick_return_yards' => 'integer',
        'interception_returns' => 'integer',
        'interception_return_yards' => 'integer',
        'opponent_kickoffs' => 'integer',
        'opponent_kickoffs_in_end_zone' => 'integer',
        'opponent_kickoff_touchbacks' => 'integer',
        'opponent_punts_had_blocked' => 'integer',
        'opponent_punt_net_average' => 'integer',
        'opponent_extra_point_kicking_attempts' => 'integer',
        'opponent_extra_point_kicking_conversions' => 'integer',
        'opponent_extra_points_had_blocked' => 'integer',
        'opponent_extra_point_passing_attempts' => 'integer',
        'opponent_extra_point_passing_conversions' => 'integer',
        'opponent_extra_point_rushing_attempts' => 'integer',
        'opponent_extra_point_rushing_conversions' => 'integer',
        'opponent_field_goal_attempts' => 'integer',
        'opponent_field_goals_made' => 'integer',
        'opponent_field_goals_had_blocked' => 'integer',
        'opponent_punt_returns' => 'integer',
        'opponent_punt_return_yards' => 'integer',
        'opponent_kick_returns' => 'integer',
        'opponent_kick_return_yards' => 'integer',
        'opponent_interception_returns' => 'integer',
        'opponent_interception_return_yards' => 'integer',
        'solo_tackles' => 'integer',
        'assisted_tackles' => 'integer',
        'sacks' => 'integer',
        'sack_yards' => 'integer',
        'passes_defended' => 'integer',
        'fumbles_forced' => 'integer',
        'fumbles_recovered' => 'integer',
        'fumble_return_yards' => 'integer',
        'fumble_return_touchdowns' => 'integer',
        'interception_return_touchdowns' => 'integer',
        'blocked_kicks' => 'integer',
        'punt_return_touchdowns' => 'integer',
        'punt_return_long' => 'integer',
        'kick_return_touchdowns' => 'integer',
        'kick_return_long' => 'integer',
        'blocked_kick_return_yards' => 'integer',
        'blocked_kick_return_touchdowns' => 'integer',
        'field_goal_return_yards' => 'integer',
        'field_goal_return_touchdowns' => 'integer',
        'punt_net_yards' => 'integer',
        'opponent_solo_tackles' => 'integer',
        'opponent_assisted_tackles' => 'integer',
        'opponent_sacks' => 'integer',
        'opponent_sack_yards' => 'integer',
        'opponent_passes_defended' => 'integer',
        'opponent_fumbles_forced' => 'integer',
        'opponent_fumbles_recovered' => 'integer',
        'opponent_fumble_return_yards' => 'integer',
        'opponent_fumble_return_touchdowns' => 'integer',
        'opponent_interception_return_touchdowns' => 'integer',
        'opponent_blocked_kicks' => 'integer',
        'opponent_punt_return_touchdowns' => 'integer',
        'opponent_punt_return_long' => 'integer',
        'opponent_kick_return_touchdowns' => 'integer',
        'opponent_kick_return_long' => 'integer',
        'opponent_blocked_kick_return_yards' => 'integer',
        'opponent_blocked_kick_return_touchdowns' => 'integer',
        'opponent_field_goal_return_yards' => 'integer',
        'opponent_field_goal_return_touchdowns' => 'integer',
        'opponent_punt_net_yards' => 'integer',
        'team_name' => 'string',
        'games' => 'integer',
        'passing_dropbacks' => 'integer',
        'opponent_passing_dropbacks' => 'integer',
        'team_season_id' => 'integer',
        'point_differential' => 'integer',
        'passing_interception_percentage' => 'integer',
        'punt_return_average' => 'integer',
        'kick_return_average' => 'integer',
        'extra_point_percentage' => 'integer',
        'field_goal_percentage' => 'integer',
        'opponent_passing_interception_percentage' => 'integer',
        'opponent_punt_return_average' => 'integer',
        'opponent_kick_return_average' => 'integer',
        'opponent_extra_point_percentage' => 'integer',
        'opponent_field_goal_percentage' => 'integer',
        'penalty_yard_differential' => 'integer',
        'punt_return_yard_differential' => 'integer',
        'kick_return_yard_differential' => 'integer',
        'two_point_conversion_returns' => 'integer',
        'opponent_two_point_conversion_returns' => 'integer',
        'team_id' => 'integer',
        'global_team_id' => 'integer',
    ];
}
