<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Acme\FantasyDataRotoBallerNews
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NFL v3 RotoBaller Premium News
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Acme\FantasyDataRotoBallerNews;

use \Acme\FantasyDataRotoBallerNews\Configuration;
use \Acme\FantasyDataRotoBallerNews\ApiException;
use \Acme\FantasyDataRotoBallerNews\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Acme\FantasyDataRotoBallerNews
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for premiumNews
     *
     * Premium News.
     *
     */
    public function testPremiumNews()
    {
    }

    /**
     * Test case for premiumNewsByDate
     *
     * Premium News by Date.
     *
     */
    public function testPremiumNewsByDate()
    {
    }

    /**
     * Test case for premiumNewsByPlayer
     *
     * Premium News by Player.
     *
     */
    public function testPremiumNewsByPlayer()
    {
    }

    /**
     * Test case for premiumNewsByTeam
     *
     * Premium News by Team.
     *
     */
    public function testPremiumNewsByTeam()
    {
    }
}
